interface LangMapInteraface {
  [key: string]: {
    [key: string]: string;
  };
}

export enum SELECTABLE_STRINGS {
  //general
  HEADER_WELCOME = 'HEADER_WELCOME',
  MENU = 'MENU',
  REGISTER = 'REGISTER',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  NEED_HELP_Q = 'NEED_HELP_Q',
  HAS_VALUE_OUTSIDE_SUGGESTED_RANGE = 'HAS_VALUE_OUTSIDE_SUGGESTED_RANGE',
  SAVE_CALCULATION = 'SAVE_CALCULATION',
  CALCULATION_VISUALIZATION = 'CALCULATION_VISUALIZATION',
  LOADING = 'LOADING',

  //auth
  EMAIL = 'EMAIL',
  PASSWORD = 'PASSWORD',
  PASSWORD_CONFIRM = 'PASSWORD_CONFIRM',
  SUBMIT = 'SUBMIT',
  NO_ACC_Q = 'NO_ACC_Q',
  HAVE_ACC_Q = 'HAVE_ACC_Q',

  INVALID_EMAIL = 'INVALID_EMAIL',
  PASSWORD_MIN = 'PASSWORD_MIN',
  PASSWORD_HAS_LOWER = 'PASSWORD_HAS_LOWER',
  PASSWORD_HAS_UPPER = 'PASSWORD_HAS_UPPER',
  PASSWORD_HAS_NUMBER = 'PASSWORD_HAS_NUMBER',
  PASSWORD_HAS_SYMBOL = 'PASSWORD_HAS_SYMBOL',
  PASSWORDS_DONT_MATCH = 'PASSWORDS_DONT_MATCH',

  //info
  TOAST_ERROR = 'TOAST_ERROR',
  TOAST_ERROR_SESSION_EXPIRED = 'TOAST_ERROR_SESSION_EXPIRED',
  TOAST_ERROR_LOADING_DATA = 'TOAST_ERROR_LOADING_DATA',
  TOAST_ERROR_NOT_LOGGED_IN = 'TOAST_ERROR_NOT_LOGGED_IN',
  TOAST_ERROR_NO_PLANT_SELECTED = 'TOAST_ERROR_NO_PLANT_SELECTED',
  TOAST_SAVE_SUCCESS = 'TOAST_SAVE_SUCCESS',
  TOAST_REGISTER_SUCCESS = 'TOAST_REGISTER_SUCCESS',
  TOAST_LOGIN_SUCCESS = 'TOAST_LOGIN_SUCCESS',
  TOAST_LOGOUT_SUCCESS = 'TOAST_LOGOUT_SUCCESS',
  TOAST_TRY_AGAIN_LATER = 'TOAST_TRY_AGAIN_LATER',

  //settings
  SETTINGS = 'SETTINGS',
  SETTINGS_PREF_UNIT_OF_MEASUREMENT = 'SETTINGS_PREF_UNIT_OF_MEASUREMENT',
  SETTINGS_THEME = 'SETTINGS_THEME',
  SETTINGS_LANGUAGE = 'SETTINGS_LANGUAGE',
  SETTINGS_PREF_UNIT_OF_MEASUREMENT_ACRES = 'SETTINGS_PREF_UNIT_OF_MEASUREMENT_ACRES',
  SETTINGS_PREF_UNIT_OF_MEASUREMENT_ACRES_SYMBOL = 'SETTINGS_PREF_UNIT_OF_MEASUREMENT_ACRES_SYMBOL',
  SETTINGS_PREF_UNIT_OF_MEASUREMENT_HECTARES = 'SETTINGS_PREF_UNIT_OF_MEASUREMENT_HECTARES',
  SETTINGS_PREF_UNIT_OF_MEASUREMENT_HECTARES_SYMBOL = 'SETTINGS_PREF_UNIT_OF_MEASUREMENT_HECTARES_SYMBOL',

  //settings themes
  THEME_LIGHT = 'light',
  THEME_DARK = 'dark',
  THEME_SYSTEM = 'system',

  //latin names
  // Seeding crops
  PISUM_SATIVUM = 'Pisum sativum', // Грах (Pea)
  GLYCINE_MAX = 'Glycine max', // Соя (Soybean)
  SORGHUM_VULGARE_VAR_TEHNICUM = 'Sorghum vulgare var. tehnicum', // Сорго (Sorghum)
  ZEA_MAYS = 'Zea mays', // Царевица (Corn)

  // Legumes (бобови)
  MEDICAGO_SATIVA = 'Medicago sativa', // Люцерна (Alfalfa)
  TRIFOLIUM_STELLATUM = 'Trifolium stellatum', // Звездан (Star Clover)
  TRIFOLIUM_PRATENSE = 'Trifolium pratense', // Червена детелина (Red Clover)
  TRIFOLIUM_REPENS = 'Trifolium repens', // Бяла детелина (White Clover)

  // Cereals / Grasses (зърнени / треви)
  LOLIUM_PERENNE = 'Lolium perenne', // Пасищен райграс (Perennial Ryegrass)
  AGROPYRON_CRISTATUM = 'Agropyron cristatum', // Гребенчат житняк (Crested Wheatgrass)
  DACTYLIS_GLOMERATA = 'Dactylis glomerata', // Ежова главица (Orchard Grass)
  AVENULA_PUBESCENS = 'Avenula pubescens', // Безосилеста овсига (Downy Oatgrass)
  FESTUCA_PRATENSIS = 'Festuca pratensis', // Ливадна власатка (Meadow Fescue)
  FESTUCA_RUBRA = 'Festuca rubra', // Червена власатка (Red Fescue)

  // chemical protection enemy targets
  // Балур (johnsongras)
  SORGHUM_HALEPENSE = 'Sorghum halepense',
  // Кисела трева (false nutsedge)
  CYPERUS_STRIGOSUS = 'Cyperus strigosus',
  // Кокоше просо (barnyard grass)
  ECHINOCHLOA_CRUS_GALLI = 'Echinochloa crus-galli',
  // Кръвно просо (hairy crabgrass)
  DIGITARIA_SANGUINALIS = 'Digitaria sanguinalis',
  // Кощрява (setaria)
  SETARIA_SPP = 'Setaria spp.',
  // Метлица (apera)
  APERA_SPР = 'Apera spр.',
  // Овчарска торбичка (shepherd's purse)
  CAPSELLA_BURSA_PASTORIS = 'Capsella bursa-pastoris',
  // Тученица (pursley)
  PORTULACA_OLERACEA = 'Portulaca oleracea',
  // Черно куче грозде (black nightshade)
  SOLANUM_NIGRUM = 'Solanum nigrum',
  // Щир (amaranths)
  AMARANTHUS = 'Amaranthus',
  // Лисича опашка (slender meadow foxtail)
  ALOPECURUS_MYOSUROIDES = 'Alopecurus myosuroides',
  // Райграс (ryegrass)
  LOLIUM = 'Lolium',
  // Червена мъртва коприва (redroot pigweed)
  AMARANTHUS_RETROFLEXUS = 'Amaranthus retroflexus',
  // Лобода (lamb's quarters)
  CHENOPODIUM_ALBUM = 'Chenopodium album',
  // Водно пипериче (water pepper)
  PERSICARIA_HYDROPIPER = 'Persicaria hydropiper',
  // Великденче (gypsyweed)
  VERONICA_OFFICINALIS = 'Veronica officinalis',
  // Врабчови чревца (chickweed)
  STELLARIA_MEDIA = 'Stellaria media',
  // Лайка (matricaria)
  MATRICARIA_RECUTITA = 'Matricaria recutita',
  // Дива ряпа (wild radish)
  RAPHANUS_RAPHANISTRUM = 'Raphanus raphanistrum',
  // Типове здравец (geranium)
  GERANIUM_SP = 'Geranium sp.',
  // Спореж (groundsel)
  SENECIO_VULGARIS = 'Senecio vulgaris',
  // Червена мъртва коприва (purple archangel)
  LAMIUM_PURPUREUM = 'Lamium purpureum',
  // Синап (field mustard)
  SINAPIS_ARVENSIS = 'Sinapis arvensis',
  // Полско огнивче (scarlet pimpernel)
  LYSIMACHIA_ARVENSIS = 'Lysimachia arvensis',
  // Синя метличина (cornflower)
  CENTAUREA_CYANUS = 'Centaurea cyanus',
  // Див овес (wild oat)
  AVENA_FATUA = 'Avena fatua',
  // Овсига (Bromus)
  BROMUS = 'Bromus',
  // Фаларис (phalaris)
  PHALARIS_SPP = 'Phalaris spp.',
  // Пирей (quick grass)
  ELYMUS_REPENS = 'Elymus repens',
  // Троскот (bermuda grass)
  CYNODON_DACTYLON = 'Cynodon dactylon',
  // Лепка (catchweed)
  GALIUM_APARINE = 'Galium aparine',
  // Бутрак (beggartick)
  BIDENS_TRIPARTITA = 'Bidens tripartita',
  // Поветица. (field bindweed)
  CONVOLVULUS_ARVENSIS = 'Convolvulus arvensis',
  // Ветрушка (windgrass)
  APERA_SPICA_VENTI = 'Apera spica venti',
  // Кощрява (setaria)
  APERA_SPP = 'Apera spp.',
  // Абутилон (velvetleaf)
  ABUTILON_THEOPHRASTI = 'Abutilon theophrasti',
  // Паламида (plume thistles)
  CIRSIUM_ARVENSE = 'Cirsium arvense',
  // Подрумче (mayweed)
  ANTHEMIS_ARVENSIS = 'Anthemis arvensis',
  // Синап (white mustard)
  SINAPIS_ALBA = 'Sinapis alba',
  // Грахова листна въшка (pea aphid)
  ACYRTHOSIPHON_PISI = 'Acyrthosiphon pisi',
  // Детелинов хоботник (clover seed weevil)
  PROTAPION_APRICANS = 'Protapion apricans',
  // Малък люцернов листов хоботник (alfalfa weevil)
  HYPERA_POSTICA = 'Hypera postica',
  // Детелинов зърнояд (Seed beetle)
  BRUCHIDIUS_VARIUS = 'Bruchidius varius',
  // Грахова листна въшка (aphid midge)
  APHIDOLETES_APHIDIMYZA = 'Aphidoletes aphidimyza',
  // Нощенки (owlet moths)
  NOCTUIDAE = 'Noctuidae',
  // Скакалци (grasshoppers)
  CAELIFERA = 'Caelifera',
  // Педомерки. (geometer moths)
  GEOMETRIDAE = 'Geometridae',
  // Люцернов листояд (lucerne leaf beetle)
  GONIOCTENA_FORNICATA = 'Gonioctena fornicata',
  // Люцернов листов хоботник. (alfalfa weevil)
  PHYTONOMUS_VARIABILIS = 'Phytonomus variabilis',
  // Пъпкова галица (alfalfa leaf midge)
  DASYNEURA_IGNORATA = 'Dasyneura ignorata',
  // Цветова галица (alfalfa flower midge)
  CONTARINIA_MEDICAGINIS = 'Contarinia medicaginis',
  // Маков листояд. ()
  ENTOMOSCELIS_SULTATOR = 'Entomoscelis sultator',
  // Грахова листна въшка (puceron noir de la luzerne)
  APHIS_MEDICAGINIS = 'Aphis medicaginis',
  // Татул (jimsonweeds)
  DATURA_STRAMONIUM = 'Datura stramonium',
  // Телени червеи (lined click beetle)
  AGRIOTIS_LINEATUS = 'Agriotis lineatus',
  // Галообразуващ зелев хоботник (turnip gall weevil)
  CEUTORRHYNCHUS_PLEUROSTIGMA = 'Ceutorrhynchus pleurostigma',
  // Стоножки (centipedes)
  CHILOPODA = 'Chilopoda',
  // Зелеви мухи (cabbage root fly)
  CHORTOPHILA_BRASSICAE = 'Chortophila brassicae',
  // Майски бръмбар и Телени червеи. (cockchafer)
  MELOLONTHA_MELOLONTHA = 'Melolontha melolontha',
  // Грудков хоботник (root weevil)
  SITONA_SP = 'Sitona sp.',
  // Черна бобова листна въшка (bean aphid)
  APHIS_FABAE = 'Aphis fabae',
  // Тъмна грахова листозавивачка (bean aphid)
  LASPEYRESIA_NIGRICANA = 'Laspeyresia nigricana',
  // Грахов зърнояд (pea weevil)
  BRUCHUS_PISORUM = 'Bruchus pisorum',
  // Гамозначна нощенка (silver Y)
  AUTOGRAPHA_GAMMA = 'Autographa gamma',
  // Листни въшки (greenfly)
  APHIDOIDEA = 'Aphidoidea',
  // Хоботници. (true weevils)
  CURCULIONIDAE = 'Curculionidae',
  // Акари (mites)
  ACARINA = 'Acarina',
  // Оранжерийна белокрилка. (glasshouse whitefly)
  TRIALEURODES_VAPORARIORUM = 'Trialeurodes vaporariorum',
  // Аскохитоза (chickpea ascochyta blight fungus)
  ASCOCHYTA_RABIEI = 'Ascochyta rabiei',
  // Антракноза (brown leaf spot)
  ANTHRACNOSE = 'Anthracnose',
  // Брашнеста мана (powdery mildew)
  BLUMERIA_GRAMINIS = 'Blumeria graminis',
  // Бяло гниене (white mold)
  SCLEROTINIA_SCLEROTIORUM = 'Sclerotinia sclerotiorum',
  // Бяло гниене (Grey mould)
  BOTRYTIS_CINEREA = 'Botrytis cinerea',
  // Мана (Downy mildew)
  PERONOSPORACEAE = 'Peronosporaceae',
  // Ръжда. (black rust)
  PUCCINIA_GRAMINIS = 'Puccinia graminis',
  // Септориоза (Bacterial leaf spot)
  SEPTORIA = 'Septoria',
  // Бактериоза. ()
  XANTHOMONAS = 'Xanthomonas',
  // Северен листен пригор (northern corn leaf blight)
  SETOSPHAERIA_TURCICA = 'Setosphaeria turcica',
  // Полско лютиче (buttercups)
  RANUNCULUS_ARVENSIS = 'Ranunculus arvensis',
  // Трипси (Thrips)
  THYSANOPTERA = 'Thysanoptera',
  // Обикновена житна пиявица (cereal leaf beetle)
  OULEMA_MELANOPA = 'Oulema melanopa',
  // Овесена листна въшка (grain aphid)
  SITOBION_AVENAE = 'Sitobion avenae',
  // Цикади и др. (cicadas)
  CICADOIDEA = 'Cicadoidea',
  // Западен коренов царевичен червей. (corn rootworm)
  DIABROTICA_VIRGIFERA_ZEAE = 'Diabrotica virgifera zeae',
  // Царевичен стъблен пробивач (European corn worm)
  OSTRINIA_NUBILALIS = 'Ostrinia nubilalis',
  // Ливадна пеперуда. (beet webworm)
  LOXOSTEGE_STICTICALIS = 'Loxostege sticticalis',
  // Зърнов бръмбар (American wheat weevil)
  RHYZOPERTHA_DOMINICA = 'Rhyzopertha dominica',
  // Брашнен бръмбър (yellow mealworm beetle)
  TENEBRIO_MOLITOR = 'Tenebrio molitor',
  // Сив царевичен хоботник. (maize leaf weevil)
  TANYMECUS_DILATICOLLIS = 'Tanymecus dilaticollis',
  // Питиум (bacterial stalk rot of maize)
  PYTHIUM_APHANIDERMATUM = 'Pythium aphanidermatum',
  // Фузариум (fusarium head blight)
  FUSARIUM_GRAMINEARUM = 'Fusarium graminearum',
  // Ризоктония (Leaf and sheath blight)
  RHIZOCTONIA_ZEAE = 'Rhizoctonia zeae',


  //sowing
  SOWING_RATE_CALC = 'SOWING_RATE_CALC',
  SOWING_RATE_PICK_CULTURE = 'SOWING_RATE_PICK_CULTURE',
  SOWING_RATE_SELECTED_CULTURE = 'SOWING_RATE_SELECTED_CULTURE',
  SOWING_RATE_INPUT_SUGGESTED_RANGE = 'SOWING_RATE_INPUT_SUGGESTED_RANGE',
  SOWING_RATE_INPUT_SUGGESTED_VALUE = 'SOWING_RATE_INPUT_SUGGESTED_VALUE',
  SOWING_RATE_INPUT_COEFFICIENT_SECURITY = 'SOWING_RATE_INPUT_COEFFICIENT_SECURITY',
  SOWING_RATE_INPUT_WANTED_PLANTS_PER_M2 = 'SOWING_RATE_INPUT_WANTED_PLANTS_PER_M2',
  SOWING_RATE_INPUT_MASS_PER_1000g_SEEDS = 'SOWING_RATE_INPUT_MASS_PER_1000g_SEEDS',
  SOWING_RATE_INPUT_PURITY = 'SOWING_RATE_INPUT_PURITY',
  SOWING_RATE_INPUT_GERMINATION = 'SOWING_RATE_INPUT_GERMINATION',
  SOWING_RATE_INPUT_ROW_SPACING = 'SOWING_RATE_INPUT_ROW_SPACING',
  SOWING_RATE_INPUT_TOTAL_AREA = 'SOWING_RATE_INPUT_TOTAL_AREA',
  SOWING_RATE_OUTPUT_SOWING_RATE = 'SOWING_RATE_OUTPUT_SOWING_RATE',
  SOWING_RATE_OUTPUT_SOWING_RATE_SEEDS_PER_M2 = 'SOWING_RATE_OUTPUT_SOWING_RATE_SEEDS_PER_M2',
  SOWING_RATE_OUTPUT_SOWING_RATE_PLANTS_PER_ACRE = 'SOWING_RATE_OUTPUT_SOWING_RATE_PLANTS_PER_ACRE',
  SOWING_RATE_OUTPUT_SOWING_RATE_PLANTS_PER_HECTARE = 'SOWING_RATE_OUTPUT_SOWING_RATE_PLANTS_PER_HECTARE',
  SOWING_RATE_OUTPUT_USED_SEEDS = 'SOWING_RATE_OUTPUT_USED_SEEDS',
  SOWING_RATE_OUTPUT_KA_PER_ACRE = 'SOWING_RATE_OUTPUT_KA_PER_ACRE',
  SOWING_RATE_OUTPUT_KA_PER_HECTARE = 'SOWING_RATE_OUTPUT_KA_PER_HECTARE',
  SOWING_RATE_OUTPUT_ROW_SPACING = 'SOWING_RATE_OUTPUT_ROW_SPACING',
  SOWING_RATE_OUTPUT_ROW_SPACING_CM = 'SOWING_RATE_OUTPUT_ROW_SPACING_CM',
  SOWING_RATE_THIS_IS_SUGGESTED = 'SOWING_RATE_THIS_IS_SUGGESTED',
  SOWING_RATE_VIZ = 'SOWING_RATE_VIZ',
  SOWING_RATE_VIZ_GENERAL = 'SOWING_RATE_VIZ_GENERAL',
  SOWING_RATE_VIZ_ALL_ELEMENTS = 'SOWING_RATE_VIZ_ALL_ELEMENTS',
  SOWING_RATE_VIZ_ELEMENTS_RELATIONSHIP = 'SOWING_RATE_VIZ_ELEMENTS_RELATIONSHIP',
  SOWING_RATE_VIZ_COMPARE_CALCED_PARAMS = 'SOWING_RATE_VIZ_COMPARE_CALC_PARAMS',
  SOWING_RATE_VIZ_COMPARE_CALCED_PARAMS_VECED = 'SOWING_RATE_VIZ_COMPARE_CALC_PARAMS_VECED',
  SOWING_RATE_VIZ_PLANTING_EFFICIENCY = 'SOWING_RATE_VIZ_PLANTING_EFFICIENCY',
  SOWING_RATE_VIZ_PLANTING_EFFICIENCY_SEEDS_TO_PLANTS = 'SOWING_RATE_VIZ_PLANTING_EFFICIENCY_SEEDS_TO_PLANTS',
  SOWING_RATE_VIZ_PLANTING_EFFICIENCY_COVERAGE = 'SOWING_RATE_VIZ_PLANTING_EFFICIENCY_COVERAGE',
  SOWING_RATE_VIZ_PLANTING_EFFICIENCY_DENSITY = 'SOWING_RATE_VIZ_PLANTING_EFFICIENCY_DENSITY',
  SOWING_RATE_VIZ_PLANTING_EFFICIENCY_EFFICIENCY = 'SOWING_RATE_VIZ_PLANTING_EFFICIENCY_EFFICIENCY',
  SOWING_RATE_VIZ_PLANTING_EFFICIENCY_SUGGESTED = 'SOWING_RATE_VIZ_PLANTING_EFFICIENCY_SUGGESTED',

  //combined calculator
  COMBINED_CALC_TITLE = 'COMBINED_CALC_TITLE',
  COMBINED_CALC_DESCRIPTION = 'COMBINED_CALC_DESCRIPTION',
  COMBINED_LEGUME_TITLE = 'COMBINED_LEGUME_TITLE',
  COMBINED_CEREAL_TITLE = 'COMBINED_CEREAL_TITLE',
  COMBINED_SUMMARY_TITLE = 'COMBINED_SUMMARY_TITLE',
  COMBINED_TOTAL_PARTICIPATION = 'COMBINED_TOTAL_PARTICIPATION',
  COMBINED_FINAL_PRICE = 'COMBINED_FINAL_PRICE',
  COMBINED_VALUES_OUTSIDE_LIMIT = 'COMBINED_VALUES_OUTSIDE_LIMIT',
  COMBINED_SAVE_CALCULATION = 'COMBINED_SAVE_CALCULATION',
  COMBINED_VISUALIZATION_TITLE = 'COMBINED_VISUALIZATION_TITLE',
  COMBINED_VISUALIZATION_DESCRIPTION = 'COMBINED_VISUALIZATION_DESCRIPTION',
  COMBINED_TOTAL_PARTICIPATION_LABEL = 'COMBINED_TOTAL_PARTICIPATION_LABEL',
  COMBINED_MAX_PARTICIPATION = 'COMBINED_MAX_PARTICIPATION',
  COMBINED_ACTIVE = 'COMBINED_ACTIVE',
  COMBINED_PLEASE_SELECT_PLANT = 'COMBINED_PLEASE_SELECT_PLANT',
  COMBINED_PLANT = 'COMBINED_PLANT',
  COMBINED_SOWING_RATE = 'COMBINED_SOWING_RATE',
  COMBINED_SOWING_RATE_SINGLE = 'COMBINED_SOWING_RATE_SINGLE',
  COMBINED_PARTICIPATION_PERCENT = 'COMBINED_PARTICIPATION_PERCENT',
  COMBINED_SOWING_RATE_MIX = 'COMBINED_SOWING_RATE_MIX',
  COMBINED_SEED_PRICE_PER_ACRE = 'COMBINED_SEED_PRICE_PER_ACRE',
  COMBINED_SOWING_RATE_BY_PLANT_TYPE = 'COMBINED_SOWING_RATE_BY_PLANT_TYPE',
  COMBINED_PARTICIPATION_DISTRIBUTION = 'COMBINED_PARTICIPATION_DISTRIBUTION',
  COMBINED_PRICE_PER_ACRE_COMPARISON = 'COMBINED_PRICE_PER_ACRE_COMPARISON',
  COMBINED_PRICE_PER_ACRE_COMPARISON_LABEL = 'COMBINED_PRICE_PER_ACRE_COMPARISON_LABEL',
  COMBINED_PRICE_PER_HECTARE_COMPARISON = 'COMBINED_PRICE_PER_HECTARE_COMPARISON',
  COMBINED_PRICE_PER_HECTARE_COMPARISON_LABEL = 'COMBINED_PRICE_PER_HECTARE_COMPARISON_LABEL',
  COMBINED_SOWING_RATE_COMPARISON = 'COMBINED_SOWING_RATE_COMPARISON',
  COMBINED_SOWING_RATE_SINGLE_PLANT = 'COMBINED_SOWING_RATE_SINGLE_PLANT',
  COMBINED_SOWING_RATE_MIX_PLANT = 'COMBINED_SOWING_RATE_MIX_PLANT',

  //chemical protection
  CHEMICAL_PROTECTION_TITLE = 'CHEMICAL_PROTECTION_TITLE',
  CHEMICAL_PROTECTION_DESCRIPTION = 'CHEMICAL_PROTECTION_DESCRIPTION',
  CHEMICAL_PROTECTION_SELECT_CHEMICAL = 'CHEMICAL_PROTECTION_SELECT_CHEMICAL',

  CHEMICAL_PROTECTION_NONE_REGISTERED_FOR_SORGHUM = 'CHEMICAL_PROTECTION_NONE_REGISTERED_FOR_SORGHUM',

  CHEMICAL_PROTECTION_CHEM_DUAL_GOLD_960_EC = 'CHEMICAL_PROTECTION_CHEM_DUAL_GOLD_960_EC',
  CHEMICAL_PROTECTION_CHEM_DUAL_GOLD_960_EC_INFO = 'CHEMICAL_PROTECTION_CHEM_DUAL_GOLD_960_EC_INFO',
  CHEMICAL_PROTECTION_CHEM_DUAL_GOLD_960_EC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_DUAL_GOLD_960_EC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_EKLIPS_70_VDG = 'CHEMICAL_PROTECTION_CHEM_EKLIPS_70_VDG',
  CHEMICAL_PROTECTION_CHEM_EKLIPS_70_VDG_INFO = 'CHEMICAL_PROTECTION_CHEM_EKLIPS_70_VDG_INFO',
  CHEMICAL_PROTECTION_CHEM_EKLIPS_70_VDG_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_EKLIPS_70_VDG_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_LEOPARD_5_EC = 'CHEMICAL_PROTECTION_CHEM_LEOPARD_5_EC',
  CHEMICAL_PROTECTION_CHEM_LEOPARD_5_EC_INFO = 'CHEMICAL_PROTECTION_CHEM_LEOPARD_5_EC_INFO',
  CHEMICAL_PROTECTION_CHEM_LEOPARD_5_EC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_LEOPARD_5_EC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_LENTAGRAN_45_WP = 'CHEMICAL_PROTECTION_CHEM_LENTAGRAN_45_WP',
  CHEMICAL_PROTECTION_CHEM_LENTAGRAN_45_WP_INFO = 'CHEMICAL_PROTECTION_CHEM_LENTAGRAN_45_WP_INFO',
  CHEMICAL_PROTECTION_CHEM_LENTAGRAN_45_WP_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_LENTAGRAN_45_WP_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_PULSAR_40_SL = 'CHEMICAL_PROTECTION_CHEM_PULSAR_40_SL',
  CHEMICAL_PROTECTION_CHEM_PULSAR_40_SL_INFO = 'CHEMICAL_PROTECTION_CHEM_PULSAR_40_SL_INFO',
  CHEMICAL_PROTECTION_CHEM_PULSAR_40_SL_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_PULSAR_40_SL_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_DECIS_100_EC = 'CHEMICAL_PROTECTION_CHEM_DECIS_100_EC',
  CHEMICAL_PROTECTION_CHEM_DECIS_100_EC_INFO = 'CHEMICAL_PROTECTION_CHEM_DECIS_100_EC_INFO',
  CHEMICAL_PROTECTION_CHEM_DECIS_100_EC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_DECIS_100_EC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_LAMDEX_EXTRA = 'CHEMICAL_PROTECTION_CHEM_LAMDEX_EXTRA',
  CHEMICAL_PROTECTION_CHEM_LAMDEX_EXTRA_INFO = 'CHEMICAL_PROTECTION_CHEM_LAMDEX_EXTRA_INFO',
  CHEMICAL_PROTECTION_CHEM_LAMDEX_EXTRA_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_LAMDEX_EXTRA_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_METEOR = 'CHEMICAL_PROTECTION_CHEM_METEOR',
  CHEMICAL_PROTECTION_CHEM_METEOR_INFO = 'CHEMICAL_PROTECTION_CHEM_METEOR_INFO',
  CHEMICAL_PROTECTION_CHEM_METEOR_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_METEOR_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_SUMI_ALPHA_5_EC = 'CHEMICAL_PROTECTION_CHEM_SUMI_ALPHA_5_EC',
  CHEMICAL_PROTECTION_CHEM_SUMI_ALPHA_5_EC_INFO = 'CHEMICAL_PROTECTION_CHEM_SUMI_ALPHA_5_EC_INFO',
  CHEMICAL_PROTECTION_CHEM_SUMI_ALPHA_5_EC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_SUMI_ALPHA_5_EC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_MOSPILAN_20_SG = 'CHEMICAL_PROTECTION_CHEM_MOSPILAN_20_SG',
  CHEMICAL_PROTECTION_CHEM_MOSPILAN_20_SG_INFO = 'CHEMICAL_PROTECTION_CHEM_MOSPILAN_20_SG_INFO',
  CHEMICAL_PROTECTION_CHEM_STOMP_AQUA = 'CHEMICAL_PROTECTION_CHEM_STOMP_AQUA',
  CHEMICAL_PROTECTION_CHEM_STOMP_AQUA_INFO = 'CHEMICAL_PROTECTION_CHEM_STOMP_AQUA_INFO',
  CHEMICAL_PROTECTION_CHEM_STOMP_AQUA_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_STOMP_AQUA_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_CHALLENGE_600_SC = 'CHEMICAL_PROTECTION_CHEM_CHALLENGE_600_SC',
  CHEMICAL_PROTECTION_CHEM_CHALLENGE_600_SC_INFO = 'CHEMICAL_PROTECTION_CHEM_CHALLENGE_600_SC_INFO',
  CHEMICAL_PROTECTION_CHEM_CHALLENGE_600_SC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_CHALLENGE_600_SC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_STRATOS_ULTRA = 'CHEMICAL_PROTECTION_CHEM_STRATOS_ULTRA',
  CHEMICAL_PROTECTION_CHEM_STRATOS_ULTRA_INFO = 'CHEMICAL_PROTECTION_CHEM_STRATOS_ULTRA_INFO',
  CHEMICAL_PROTECTION_CHEM_STRATOS_ULTRA_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_STRATOS_ULTRA_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_ACHIBA_MAX = 'CHEMICAL_PROTECTION_CHEM_ACHIBA_MAX',
  CHEMICAL_PROTECTION_CHEM_ACHIBA_MAX_INFO = 'CHEMICAL_PROTECTION_CHEM_ACHIBA_MAX_INFO',
  CHEMICAL_PROTECTION_CHEM_ACHIBA_MAX_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_ACHIBA_MAX_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_CORUM = 'CHEMICAL_PROTECTION_CHEM_CORUM',
  CHEMICAL_PROTECTION_CHEM_CORUM_INFO = 'CHEMICAL_PROTECTION_CHEM_CORUM_INFO',
  CHEMICAL_PROTECTION_CHEM_CORUM_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_CORUM_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_LEBRON_0_5_G = 'CHEMICAL_PROTECTION_CHEM_LEBRON_0_5_G',
  CHEMICAL_PROTECTION_CHEM_LEBRON_0_5_G_INFO = 'CHEMICAL_PROTECTION_CHEM_LEBRON_0_5_G_INFO',
  CHEMICAL_PROTECTION_CHEM_LEBRON_0_5_G_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_LEBRON_0_5_G_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_OASIS_5_EC = 'CHEMICAL_PROTECTION_CHEM_OASIS_5_EC',
  CHEMICAL_PROTECTION_CHEM_OASIS_5_EC_INFO = 'CHEMICAL_PROTECTION_CHEM_OASIS_5_EC_INFO',
  CHEMICAL_PROTECTION_CHEM_OASIS_5_EC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_OASIS_5_EC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_CITRINE_MAX = 'CHEMICAL_PROTECTION_CHEM_CITRINE_MAX',
  CHEMICAL_PROTECTION_CHEM_CITRINE_MAX_INFO = 'CHEMICAL_PROTECTION_CHEM_CITRINE_MAX_INFO',
  CHEMICAL_PROTECTION_CHEM_CITRINE_MAX_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_CITRINE_MAX_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_FLIPPER = 'CHEMICAL_PROTECTION_CHEM_FLIPPER',
  CHEMICAL_PROTECTION_CHEM_FLIPPER_INFO = 'CHEMICAL_PROTECTION_CHEM_FLIPPER_INFO',
  CHEMICAL_PROTECTION_CHEM_FLIPPER_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_FLIPPER_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_ORTIVA_TOP_SC = 'CHEMICAL_PROTECTION_CHEM_ORTIVA_TOP_SC',
  CHEMICAL_PROTECTION_CHEM_ORTIVA_TOP_SC_INFO = 'CHEMICAL_PROTECTION_CHEM_ORTIVA_TOP_SC_INFO',
  CHEMICAL_PROTECTION_CHEM_ORTIVA_TOP_SC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_ORTIVA_TOP_SC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_SWITCH_625_WG = 'CHEMICAL_PROTECTION_CHEM_SWITCH_625_WG',
  CHEMICAL_PROTECTION_CHEM_SWITCH_625_WG_INFO = 'CHEMICAL_PROTECTION_CHEM_SWITCH_625_WG_INFO',
  CHEMICAL_PROTECTION_CHEM_SWITCH_625_WG_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_SWITCH_625_WG_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_BORDEAUX_MIX_20_VP = 'CHEMICAL_PROTECTION_CHEM_BORDEAUX_MIX_20_VP',
  CHEMICAL_PROTECTION_CHEM_BORDEAUX_MIX_20_VP_INFO = 'CHEMICAL_PROTECTION_CHEM_BORDEAUX_MIX_20_VP_INFO',
  CHEMICAL_PROTECTION_CHEM_BORDEAUX_MIX_20_VP_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_BORDEAUX_MIX_20_VP_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_SULPHUR_WG = 'CHEMICAL_PROTECTION_CHEM_SULPHUR_WG',
  CHEMICAL_PROTECTION_CHEM_SULPHUR_WG_INFO = 'CHEMICAL_PROTECTION_CHEM_SULPHUR_WG_INFO',
  CHEMICAL_PROTECTION_CHEM_SULPHUR_WG_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_SULPHUR_WG_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_ZOXIS_250_SC = 'CHEMICAL_PROTECTION_CHEM_ZOXIS_250_SC',
  CHEMICAL_PROTECTION_CHEM_ZOXIS_250_SC_INFO = 'CHEMICAL_PROTECTION_CHEM_ZOXIS_250_SC_INFO',
  CHEMICAL_PROTECTION_CHEM_ZOXIS_250_SC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_ZOXIS_250_SC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_SIRTAKI = 'CHEMICAL_PROTECTION_CHEM_SIRTAKI',
  CHEMICAL_PROTECTION_CHEM_SIRTAKI_INFO = 'CHEMICAL_PROTECTION_CHEM_SIRTAKI_INFO',
  CHEMICAL_PROTECTION_CHEM_SIRTAKI_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_SIRTAKI_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_SALTUS = 'CHEMICAL_PROTECTION_CHEM_SALTUS',
  CHEMICAL_PROTECTION_CHEM_SALTUS_INFO = 'CHEMICAL_PROTECTION_CHEM_SALTUS_INFO',
  CHEMICAL_PROTECTION_CHEM_SALTUS_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_SALTUS_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_PANTHER_40_EC = 'CHEMICAL_PROTECTION_CHEM_PANTHER_40_EC',
  CHEMICAL_PROTECTION_CHEM_PANTHER_40_EC_INFO = 'CHEMICAL_PROTECTION_CHEM_PANTHER_40_EC_INFO',
  CHEMICAL_PROTECTION_CHEM_PANTHER_40_EC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_PANTHER_40_EC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_DECA_EC = 'CHEMICAL_PROTECTION_CHEM_DECA_EC',
  CHEMICAL_PROTECTION_CHEM_DECA_EC_INFO = 'CHEMICAL_PROTECTION_CHEM_DECA_EC_INFO',
  CHEMICAL_PROTECTION_CHEM_DECA_EC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_DECA_EC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_TRIKA_EXPERT = 'CHEMICAL_PROTECTION_CHEM_TRIKA_EXPERT',
  CHEMICAL_PROTECTION_CHEM_TRIKA_EXPERT_INFO = 'CHEMICAL_PROTECTION_CHEM_TRIKA_EXPERT_INFO',
  CHEMICAL_PROTECTION_CHEM_TRIKA_EXPERT_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_TRIKA_EXPERT_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_RETENGO_20_EC = 'CHEMICAL_PROTECTION_CHEM_RETENGO_20_EC',
  CHEMICAL_PROTECTION_CHEM_RETENGO_20_EC_INFO = 'CHEMICAL_PROTECTION_CHEM_RETENGO_20_EC_INFO',
  CHEMICAL_PROTECTION_CHEM_RETENGO_20_EC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_RETENGO_20_EC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_DIFKOR_250_SC = 'CHEMICAL_PROTECTION_CHEM_DIFKOR_250_SC',
  CHEMICAL_PROTECTION_CHEM_DIFKOR_250_SC_INFO = 'CHEMICAL_PROTECTION_CHEM_DIFKOR_250_SC_INFO',
  CHEMICAL_PROTECTION_CHEM_DIFKOR_250_SC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_DIFKOR_250_SC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_AGROXONE_500_SL = 'CHEMICAL_PROTECTION_CHEM_AGROXONE_500_SL',
  CHEMICAL_PROTECTION_CHEM_AGROXONE_500_SL_INFO = 'CHEMICAL_PROTECTION_CHEM_AGROXONE_500_SL_INFO',
  CHEMICAL_PROTECTION_CHEM_AGROXONE_500_SL_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_AGROXONE_500_SL_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_GENERO_480_SL = 'CHEMICAL_PROTECTION_CHEM_GENERO_480_SL',
  CHEMICAL_PROTECTION_CHEM_GENERO_480_SL_INFO = 'CHEMICAL_PROTECTION_CHEM_GENERO_480_SL_INFO',
  CHEMICAL_PROTECTION_CHEM_GENERO_480_SL_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_GENERO_480_SL_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_KIDEKA_PRO = 'CHEMICAL_PROTECTION_CHEM_KIDEKA_PRO',
  CHEMICAL_PROTECTION_CHEM_KIDEKA_PRO_INFO = 'CHEMICAL_PROTECTION_CHEM_KIDEKA_PRO_INFO',
  CHEMICAL_PROTECTION_CHEM_KIDEKA_PRO_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_KIDEKA_PRO_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_COLOMBO_PRO = 'CHEMICAL_PROTECTION_CHEM_COLOMBO_PRO',
  CHEMICAL_PROTECTION_CHEM_COLOMBO_PRO_INFO = 'CHEMICAL_PROTECTION_CHEM_COLOMBO_PRO_INFO',
  CHEMICAL_PROTECTION_CHEM_COLOMBO_PRO_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_COLOMBO_PRO_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_SIVANTO_ENERGY = 'CHEMICAL_PROTECTION_CHEM_SIVANTO_ENERGY',
  CHEMICAL_PROTECTION_CHEM_SIVANTO_ENERGY_INFO = 'CHEMICAL_PROTECTION_CHEM_SIVANTO_ENERGY_INFO',
  CHEMICAL_PROTECTION_CHEM_SIVANTO_ENERGY_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_SIVANTO_ENERGY_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_BISMARCK_KS = 'CHEMICAL_PROTECTION_CHEM_BISMARCK_KS',
  CHEMICAL_PROTECTION_CHEM_BISMARCK_KS_INFO = 'CHEMICAL_PROTECTION_CHEM_BISMARCK_KS_INFO',
  CHEMICAL_PROTECTION_CHEM_BISMARCK_KS_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_BISMARCK_KS_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_ARRAT = 'CHEMICAL_PROTECTION_CHEM_ARRAT',
  CHEMICAL_PROTECTION_CHEM_ARRAT_INFO = 'CHEMICAL_PROTECTION_CHEM_ARRAT_INFO',
  CHEMICAL_PROTECTION_CHEM_ARRAT_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_ARRAT_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_AMINOPIELIK_600_SL = 'CHEMICAL_PROTECTION_CHEM_AMINOPIELIK_600_SL',
  CHEMICAL_PROTECTION_CHEM_AMINOPIELIK_600_SL_INFO = 'CHEMICAL_PROTECTION_CHEM_AMINOPIELIK_600_SL_INFO',
  CHEMICAL_PROTECTION_CHEM_AMINOPIELIK_600_SL_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_AMINOPIELIK_600_SL_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_JANERO_480_SL = 'CHEMICAL_PROTECTION_CHEM_JANERO_480_SL',
  CHEMICAL_PROTECTION_CHEM_JANERO_480_SL_INFO = 'CHEMICAL_PROTECTION_CHEM_JANERO_480_SL_INFO',
  CHEMICAL_PROTECTION_CHEM_JANERO_480_SL_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_JANERO_480_SL_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_CORAGEN_20_SC = 'CHEMICAL_PROTECTION_CHEM_CORAGEN_20_SC',
  CHEMICAL_PROTECTION_CHEM_CORAGEN_20_SC_INFO = 'CHEMICAL_PROTECTION_CHEM_CORAGEN_20_SC_INFO',
  CHEMICAL_PROTECTION_CHEM_CORAGEN_20_SC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_CORAGEN_20_SC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_K_OBIOL_6_ULV = 'CHEMICAL_PROTECTION_CHEM_K_OBIOL_6_ULV',
  CHEMICAL_PROTECTION_CHEM_K_OBIOL_6_ULV_INFO = 'CHEMICAL_PROTECTION_CHEM_K_OBIOL_6_ULV_INFO',
  CHEMICAL_PROTECTION_CHEM_K_OBIOL_6_ULV_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_K_OBIOL_6_ULV_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_INAZUMA = 'CHEMICAL_PROTECTION_CHEM_INAZUMA',
  CHEMICAL_PROTECTION_CHEM_INAZUMA_INFO = 'CHEMICAL_PROTECTION_CHEM_INAZUMA_INFO',
  CHEMICAL_PROTECTION_CHEM_INAZUMA_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_INAZUMA_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_REDIGO_M = 'CHEMICAL_PROTECTION_CHEM_REDIGO_M',
  CHEMICAL_PROTECTION_CHEM_REDIGO_M_INFO = 'CHEMICAL_PROTECTION_CHEM_REDIGO_M_INFO',
  CHEMICAL_PROTECTION_CHEM_REDIGO_M_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_REDIGO_M_INFO_NOTES',



  CHEMICAL_PROTECTION_ACTIVE_INGREDIENTS = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENTS',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_S_METOLACHLOR = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_S_METOLACHLOR',

  CHEMICAL_PROTECTION_ENEMY_TARGETS = 'CHEMICAL_PROTECTION_ENEMY_TARGETS',
  CHEMICAL_PROTECTION_ENEMY_TARGET_JOHNSON_GRASS = 'CHEMICAL_PROTECTION_ENEMY_TARGET_JOHNSON_GRASS',
}

const LangMap: LangMapInteraface = {
  BG: {
    //plants
    [SELECTABLE_STRINGS.PISUM_SATIVUM]: 'Грах',
    [SELECTABLE_STRINGS.GLYCINE_MAX]: 'Соя',
    [SELECTABLE_STRINGS.SORGHUM_VULGARE_VAR_TEHNICUM]: 'Сорго',
    [SELECTABLE_STRINGS.ZEA_MAYS]: 'Царевица',
    [SELECTABLE_STRINGS.MEDICAGO_SATIVA]: 'Люцерна',
    [SELECTABLE_STRINGS.TRIFOLIUM_STELLATUM]: 'Звездан',
    [SELECTABLE_STRINGS.TRIFOLIUM_PRATENSE]: 'Червена детелина',
    [SELECTABLE_STRINGS.TRIFOLIUM_REPENS]: 'Бяла детелина',
    [SELECTABLE_STRINGS.LOLIUM_PERENNE]: 'Пасищен райграс',
    [SELECTABLE_STRINGS.AGROPYRON_CRISTATUM]: 'Гребенчат житняк',
    [SELECTABLE_STRINGS.DACTYLIS_GLOMERATA]: 'Ежова главица',
    [SELECTABLE_STRINGS.AVENULA_PUBESCENS]: 'Безосилеста овсига',
    [SELECTABLE_STRINGS.FESTUCA_PRATENSIS]: 'Ливадна власатка',
    [SELECTABLE_STRINGS.FESTUCA_RUBRA]: 'Червена власатка',

    [SELECTABLE_STRINGS.THEME_LIGHT]: 'Светла тема',
    [SELECTABLE_STRINGS.THEME_DARK]: 'Тъмна тема',
    [SELECTABLE_STRINGS.THEME_SYSTEM]: 'Системна тема',

    [SELECTABLE_STRINGS.HEADER_WELCOME]: 'Добре дошли, ',
    [SELECTABLE_STRINGS.MENU]: 'Меню',
    [SELECTABLE_STRINGS.REGISTER]: 'Регистрация',
    [SELECTABLE_STRINGS.LOGIN]: 'Вход',
    [SELECTABLE_STRINGS.LOGOUT]: 'Изход',
    [SELECTABLE_STRINGS.NEED_HELP_Q]: 'Нуждаете се от помощ?',
    [SELECTABLE_STRINGS.HAS_VALUE_OUTSIDE_SUGGESTED_RANGE]: 'Имате стойност извън препоръчаните!',
    [SELECTABLE_STRINGS.SAVE_CALCULATION]: 'Запази калкулацията',
    [SELECTABLE_STRINGS.CALCULATION_VISUALIZATION]: 'Визуализация на калкулацията',
    [SELECTABLE_STRINGS.LOADING]: 'Зареждане...',

    [SELECTABLE_STRINGS.EMAIL]: 'Имейл',
    [SELECTABLE_STRINGS.PASSWORD]: 'Парола',
    [SELECTABLE_STRINGS.PASSWORD_CONFIRM]: 'Потвърди парола',
    [SELECTABLE_STRINGS.SUBMIT]: 'Изпрати',
    [SELECTABLE_STRINGS.NO_ACC_Q]: 'Нямате акаунт?',
    [SELECTABLE_STRINGS.HAVE_ACC_Q]: 'Имате акаунт?',

    [SELECTABLE_STRINGS.INVALID_EMAIL]: 'Невалиден имейл',
    [SELECTABLE_STRINGS.PASSWORD_MIN]: 'Паролата трябва да е поне 6 символа',
    [SELECTABLE_STRINGS.PASSWORD_HAS_LOWER]: 'Паролата трябва да съдържа поне една малка буква',
    [SELECTABLE_STRINGS.PASSWORD_HAS_UPPER]: 'Паролата трябва да съдържа поне една главна буква',
    [SELECTABLE_STRINGS.PASSWORD_HAS_NUMBER]: 'Паролата трябва да съдържа поне една цифра',
    [SELECTABLE_STRINGS.PASSWORD_HAS_SYMBOL]:
      'Паролата трябва да съдържа поне един специален символ',
    [SELECTABLE_STRINGS.PASSWORDS_DONT_MATCH]: 'Паролите не съвпадат',

    [SELECTABLE_STRINGS.TOAST_ERROR]: 'Възникна грешка',
    [SELECTABLE_STRINGS.TOAST_ERROR_SESSION_EXPIRED]: 'Вашата сесия е изтекла. Моля влезте отново.',
    [SELECTABLE_STRINGS.TOAST_ERROR_LOADING_DATA]: 'Възникна грешка при зареждането на данните',
    [SELECTABLE_STRINGS.TOAST_ERROR_NOT_LOGGED_IN]: 'Трябва да сте влезли в профила си, за да запазите изчислението!',
    [SELECTABLE_STRINGS.TOAST_ERROR_NO_PLANT_SELECTED]: 'Не сте избрали растение за изчисление!',
    [SELECTABLE_STRINGS.TOAST_SAVE_SUCCESS]: 'Изчислението е запазено успешно!',
    [SELECTABLE_STRINGS.TOAST_REGISTER_SUCCESS]: 'Успешна регистрация! Моля влезте.',
    [SELECTABLE_STRINGS.TOAST_LOGIN_SUCCESS]: 'Успешен вход!',
    [SELECTABLE_STRINGS.TOAST_LOGOUT_SUCCESS]: 'Успешен изход!',
    [SELECTABLE_STRINGS.TOAST_TRY_AGAIN_LATER]: 'Моля опитайте по-късно',

    [SELECTABLE_STRINGS.SETTINGS]: 'Настройки',
    [SELECTABLE_STRINGS.SETTINGS_PREF_UNIT_OF_MEASUREMENT]: 'Предпочитана единица за измерване',
    [SELECTABLE_STRINGS.SETTINGS_THEME]: 'Тема',
    [SELECTABLE_STRINGS.SETTINGS_LANGUAGE]: 'Език',
    [SELECTABLE_STRINGS.SETTINGS_PREF_UNIT_OF_MEASUREMENT_ACRES]: 'Декари',
    [SELECTABLE_STRINGS.SETTINGS_PREF_UNIT_OF_MEASUREMENT_ACRES_SYMBOL]: 'дка',
    [SELECTABLE_STRINGS.SETTINGS_PREF_UNIT_OF_MEASUREMENT_HECTARES]: 'Хектари',
    [SELECTABLE_STRINGS.SETTINGS_PREF_UNIT_OF_MEASUREMENT_HECTARES_SYMBOL]: 'ha',

    [SELECTABLE_STRINGS.SOWING_RATE_CALC]: 'Калкулатор за сеитбена норма',
    [SELECTABLE_STRINGS.SOWING_RATE_PICK_CULTURE]: 'Изберете култура',
    [SELECTABLE_STRINGS.SOWING_RATE_SELECTED_CULTURE]: 'Избрана култура',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_SUGGESTED_RANGE]: 'Препоръчителен диапазон',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_SUGGESTED_VALUE]: 'Препоръчителна стойност',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_COEFFICIENT_SECURITY]: 'Коефициент на сигурност',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_WANTED_PLANTS_PER_M2]: 'Желани растения на m²',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_MASS_PER_1000g_SEEDS]: 'Маса на 1000g семена',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_PURITY]: 'Чистота',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_GERMINATION]: 'Лабораторна кълняемост',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_ROW_SPACING]: 'Междуредно разстояние',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_TOTAL_AREA]: 'Обща площ',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_SOWING_RATE]: 'Сеитбена норма',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_SOWING_RATE_SEEDS_PER_M2]: 'брой семена на m²',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_SOWING_RATE_PLANTS_PER_ACRE]: 'брой растения на дка',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_SOWING_RATE_PLANTS_PER_HECTARE]: 'брой растения на хектар',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_USED_SEEDS]: 'Използвани семена',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_KA_PER_ACRE]: 'кг/дка',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_KA_PER_HECTARE]: 'кг/хектар',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_ROW_SPACING]: 'Междуредно разстояние',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_ROW_SPACING_CM]: 'см',
    [SELECTABLE_STRINGS.SOWING_RATE_THIS_IS_SUGGESTED]:
      'Това е препоръчителната сеитбена норма базирана на въведените от вас параметри. Може да варира според конкретните условия на полето.',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ]: 'Визуализация на калкулацията',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_GENERAL]: 'Графично представяне на резултатите за',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_ALL_ELEMENTS]: 'Обща визуализация на параметрите',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_ELEMENTS_RELATIONSHIP]: 'Пропорции между параметрите',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_COMPARE_CALCED_PARAMS]:
      'Сравнение на изчислените стойности',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_COMPARE_CALCED_PARAMS_VECED]:
      'Стойностите са мащабирани за по-добра визуализация',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_PLANTING_EFFICIENCY]: 'Ефективност на сеитбата',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_PLANTING_EFFICIENCY_SEEDS_TO_PLANTS]: 'Семена→Растения',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_PLANTING_EFFICIENCY_COVERAGE]: 'Покритие',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_PLANTING_EFFICIENCY_DENSITY]: 'Гъстота',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_PLANTING_EFFICIENCY_EFFICIENCY]: 'Ефективност',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_PLANTING_EFFICIENCY_SUGGESTED]:
      'Относителни показатели за качество на сеитбата',

    [SELECTABLE_STRINGS.COMBINED_CALC_TITLE]: 'Сеитбена норма на смеска',
    [SELECTABLE_STRINGS.COMBINED_CALC_DESCRIPTION]: 'Изчислете точната сеитбена норма за вашите смески от култури',
    [SELECTABLE_STRINGS.COMBINED_LEGUME_TITLE]: 'Многогодишни бобови фуражни култури',
    [SELECTABLE_STRINGS.COMBINED_CEREAL_TITLE]: 'Многогодишни житни фуражни култури',
    [SELECTABLE_STRINGS.COMBINED_SUMMARY_TITLE]: 'Обобщение на смеската',
    [SELECTABLE_STRINGS.COMBINED_TOTAL_PARTICIPATION]: 'Общо участие в смеската:',
    [SELECTABLE_STRINGS.COMBINED_FINAL_PRICE]: 'Крайна цена:',
    [SELECTABLE_STRINGS.COMBINED_VALUES_OUTSIDE_LIMIT]: 'Имате стойности извън препоръчани лимит!',
    [SELECTABLE_STRINGS.COMBINED_SAVE_CALCULATION]: 'Запази тази сметка',
    [SELECTABLE_STRINGS.COMBINED_VISUALIZATION_TITLE]: 'Визуализация на смеската',
    [SELECTABLE_STRINGS.COMBINED_VISUALIZATION_DESCRIPTION]: 'Графично представяне на участието на културите в смеската',
    [SELECTABLE_STRINGS.COMBINED_TOTAL_PARTICIPATION_LABEL]: 'Общо участие',
    [SELECTABLE_STRINGS.COMBINED_MAX_PARTICIPATION]: 'Максимално',
    [SELECTABLE_STRINGS.COMBINED_ACTIVE]: 'Активно?',
    [SELECTABLE_STRINGS.COMBINED_PLANT]: 'Растиение',
    [SELECTABLE_STRINGS.COMBINED_PLEASE_SELECT_PLANT]: 'Моля, изберете',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE_SINGLE]: 'Сеидбена норма - самостоятелно',
    [SELECTABLE_STRINGS.COMBINED_PARTICIPATION_PERCENT]: 'Участие (%)',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE]: 'Сеитбена норма',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE_MIX]: 'Сеидбена норма - в смеската',
    [SELECTABLE_STRINGS.COMBINED_SEED_PRICE_PER_ACRE]: 'Цена на семена за дка/BGN',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE_BY_PLANT_TYPE]: 'Сеитбена норма по тип култура',
    [SELECTABLE_STRINGS.COMBINED_PARTICIPATION_DISTRIBUTION]: 'Разпределение на участията',
    [SELECTABLE_STRINGS.COMBINED_PRICE_PER_ACRE_COMPARISON]: 'Сравнение на цената на семената за дка',
    [SELECTABLE_STRINGS.COMBINED_PRICE_PER_ACRE_COMPARISON_LABEL]: 'Цена на семена за дка/BGN',
    [SELECTABLE_STRINGS.COMBINED_PRICE_PER_HECTARE_COMPARISON]: 'Сравнение на цената на семената за хектар',
    [SELECTABLE_STRINGS.COMBINED_PRICE_PER_HECTARE_COMPARISON_LABEL]: 'Цена на семена за хектар/BGN',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE_COMPARISON]: 'Сравнение на сеитбените норми',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE_SINGLE_PLANT]: 'Сеитбена норма - самостоятелно',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE_MIX_PLANT]: 'Сеитбена норма - в смеската',

    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_NONE_REGISTERED_FOR_SORGHUM]: 'В единния регистър на продуктите за растителна защита и фитосанитарен контрол на БАБХ, съгласно изискванията на Регламент (ЕО) № 1107/2009, Закона за защита на растенията и Наредба № 5/2021 г. в Република България, не са регистрирани фунгициди за разрешаване пускането им на пазара и употреба при люцерната.',
  },
  EN: {
    //plants
    'Pisum sativum': 'Pea',
    'Glycine max': 'Soybean',
    'Sorghum vulgare var. tehnicum': 'Sorghum',
    'Zea mays': 'Corn',
    'Medicago sativa': 'Alfalfa',
    'Trifolium stellatum': 'Star clover',
    'Trifolium pratense': 'Red clover',
    'Trifolium repens': 'White clover',
    'Lolium perenne': 'Perennial ryegrass',
    'Agropyron cristatum': 'Crested wheatgrass',
    'Dactylis glomerata': 'Orchard grass',
    'Avenula pubescens': 'Downy oat',
    'Festuca pratensis': 'Meadow fescue',
    'Festuca rubra': 'Red fescue',

    //general
    [SELECTABLE_STRINGS.THEME_LIGHT]: 'Light',
    [SELECTABLE_STRINGS.THEME_DARK]: 'Dark',
    [SELECTABLE_STRINGS.THEME_SYSTEM]: 'System',

    [SELECTABLE_STRINGS.HEADER_WELCOME]: 'Welcome, ',
    [SELECTABLE_STRINGS.MENU]: 'Menu',
    [SELECTABLE_STRINGS.REGISTER]: 'Register',
    [SELECTABLE_STRINGS.LOGIN]: 'Login',
    [SELECTABLE_STRINGS.LOGOUT]: 'Logout',
    [SELECTABLE_STRINGS.NEED_HELP_Q]: 'Need help?',
    [SELECTABLE_STRINGS.HAS_VALUE_OUTSIDE_SUGGESTED_RANGE]: 'Has value outside suggested range!',
    [SELECTABLE_STRINGS.SAVE_CALCULATION]: 'Save calculation',
    [SELECTABLE_STRINGS.CALCULATION_VISUALIZATION]: 'Calculation visualization',
    [SELECTABLE_STRINGS.LOADING]: 'Loading...',

    [SELECTABLE_STRINGS.EMAIL]: 'Email',
    [SELECTABLE_STRINGS.PASSWORD]: 'Password',
    [SELECTABLE_STRINGS.PASSWORD_CONFIRM]: 'Confirm password',

    [SELECTABLE_STRINGS.SUBMIT]: 'Submit',
    [SELECTABLE_STRINGS.NO_ACC_Q]: "Don't have an account?",
    [SELECTABLE_STRINGS.HAVE_ACC_Q]: 'Already have an account?',

    [SELECTABLE_STRINGS.INVALID_EMAIL]: 'Invalid email',
    [SELECTABLE_STRINGS.PASSWORD_MIN]: 'Password must be at least 6 characters',
    [SELECTABLE_STRINGS.PASSWORD_HAS_LOWER]: 'Password must contain at least one lowercase letter',
    [SELECTABLE_STRINGS.PASSWORD_HAS_UPPER]: 'Password must contain at least one uppercase letter',
    [SELECTABLE_STRINGS.PASSWORD_HAS_NUMBER]: 'Password must contain at least one number',
    [SELECTABLE_STRINGS.PASSWORD_HAS_SYMBOL]:
      'Password must contain at least one special character',
    [SELECTABLE_STRINGS.PASSWORDS_DONT_MATCH]: 'Passwords do not match',

    [SELECTABLE_STRINGS.TOAST_ERROR]: 'There was an error',
    [SELECTABLE_STRINGS.TOAST_ERROR_SESSION_EXPIRED]:
      'Your session has expired. Please login again.',
    [SELECTABLE_STRINGS.TOAST_ERROR_LOADING_DATA]: 'There was an error loading the data',
    [SELECTABLE_STRINGS.TOAST_ERROR_NOT_LOGGED_IN]: 'You must be logged in to save the calculation!',
    [SELECTABLE_STRINGS.TOAST_ERROR_NO_PLANT_SELECTED]: 'You have not selected a plant for calculation!',
    [SELECTABLE_STRINGS.TOAST_SAVE_SUCCESS]: 'Calculation saved successfully!',
    [SELECTABLE_STRINGS.TOAST_REGISTER_SUCCESS]: 'Registration successful! Please log in.',
    [SELECTABLE_STRINGS.TOAST_LOGIN_SUCCESS]: 'Login successful!',
    [SELECTABLE_STRINGS.TOAST_LOGOUT_SUCCESS]: 'Logout successful!',
    [SELECTABLE_STRINGS.TOAST_TRY_AGAIN_LATER]: 'Please try again later',

    [SELECTABLE_STRINGS.SETTINGS]: 'Settings',
    [SELECTABLE_STRINGS.SETTINGS_PREF_UNIT_OF_MEASUREMENT]: 'Preferred unit of measurement',
    [SELECTABLE_STRINGS.SETTINGS_THEME]: 'Theme',
    [SELECTABLE_STRINGS.SETTINGS_LANGUAGE]: 'Language',
    [SELECTABLE_STRINGS.SETTINGS_PREF_UNIT_OF_MEASUREMENT_ACRES]: 'Acres',
    [SELECTABLE_STRINGS.SETTINGS_PREF_UNIT_OF_MEASUREMENT_ACRES_SYMBOL]: 'acre',
    [SELECTABLE_STRINGS.SETTINGS_PREF_UNIT_OF_MEASUREMENT_HECTARES]: 'Hectares',
    [SELECTABLE_STRINGS.SETTINGS_PREF_UNIT_OF_MEASUREMENT_HECTARES_SYMBOL]: 'ha',

    [SELECTABLE_STRINGS.SOWING_RATE_CALC]: 'Sowing rate calculator',
    [SELECTABLE_STRINGS.SOWING_RATE_PICK_CULTURE]: 'Pick a culture',
    [SELECTABLE_STRINGS.SOWING_RATE_SELECTED_CULTURE]: 'Selected culture',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_SUGGESTED_RANGE]: 'Suggested range',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_SUGGESTED_VALUE]: 'Suggested value',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_COEFFICIENT_SECURITY]: 'Security coefficient',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_WANTED_PLANTS_PER_M2]: 'Wanted plants per m²',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_MASS_PER_1000g_SEEDS]: 'Mass per 1000g seeds',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_PURITY]: 'Purity',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_GERMINATION]: 'Laboratory germination',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_ROW_SPACING]: 'Row spacing',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_TOTAL_AREA]: 'Total area',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_SOWING_RATE]: 'Sowing rate',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_SOWING_RATE_SEEDS_PER_M2]: 'seeds/m²',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_SOWING_RATE_PLANTS_PER_ACRE]: 'plants/acre',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_SOWING_RATE_PLANTS_PER_HECTARE]: 'plants/hectare',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_USED_SEEDS]: 'Used seeds',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_KA_PER_ACRE]: 'kg/acre',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_KA_PER_HECTARE]: 'kg/hectare',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_ROW_SPACING]: 'Row spacing',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_ROW_SPACING_CM]: 'cm',
    [SELECTABLE_STRINGS.SOWING_RATE_THIS_IS_SUGGESTED]:
      'This is the suggested sowing rate based on the parameters you have entered. It may vary depending on the specific field conditions.',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ]: 'Calculation visualization',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_GENERAL]: 'Graphical representation of the results for',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_ALL_ELEMENTS]: 'General visualization of the parameters',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_ELEMENTS_RELATIONSHIP]:
      'Proportions between the parameters',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_COMPARE_CALCED_PARAMS]:
      'Comparison of the calculated values',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_COMPARE_CALCED_PARAMS_VECED]:
      'Values are scaled for better visualization',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_PLANTING_EFFICIENCY]: 'Planting efficiency',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_PLANTING_EFFICIENCY_SEEDS_TO_PLANTS]: 'Seeds→Plants',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_PLANTING_EFFICIENCY_COVERAGE]: 'Coverage',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_PLANTING_EFFICIENCY_DENSITY]: 'Density',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_PLANTING_EFFICIENCY_EFFICIENCY]: 'Efficiency',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_PLANTING_EFFICIENCY_SUGGESTED]:
      'Relative quality indicators for sowing',

    [SELECTABLE_STRINGS.COMBINED_CALC_TITLE]: 'Mixed Seeding Rate',
    [SELECTABLE_STRINGS.COMBINED_CALC_DESCRIPTION]: 'Calculate the exact seeding rate for your crop mixtures',
    [SELECTABLE_STRINGS.COMBINED_LEGUME_TITLE]: 'Perennial Legume Forage Crops',
    [SELECTABLE_STRINGS.COMBINED_CEREAL_TITLE]: 'Perennial Cereal Forage Crops',
    [SELECTABLE_STRINGS.COMBINED_SUMMARY_TITLE]: 'Mixture Summary',
    [SELECTABLE_STRINGS.COMBINED_TOTAL_PARTICIPATION]: 'Total mixture participation:',
    [SELECTABLE_STRINGS.COMBINED_FINAL_PRICE]: 'Final price:',
    [SELECTABLE_STRINGS.COMBINED_VALUES_OUTSIDE_LIMIT]: 'You have values outside the recommended limit!',
    [SELECTABLE_STRINGS.COMBINED_SAVE_CALCULATION]: 'Save this calculation',
    [SELECTABLE_STRINGS.COMBINED_VISUALIZATION_TITLE]: 'Mixture Visualization',
    [SELECTABLE_STRINGS.COMBINED_VISUALIZATION_DESCRIPTION]: 'Graphical representation of crop participation in the mixture',
    [SELECTABLE_STRINGS.COMBINED_TOTAL_PARTICIPATION_LABEL]: 'Total participation',
    [SELECTABLE_STRINGS.COMBINED_MAX_PARTICIPATION]: 'Maximum',
    [SELECTABLE_STRINGS.COMBINED_ACTIVE]: 'Active?',
    [SELECTABLE_STRINGS.COMBINED_PLANT]: 'Plant',
    [SELECTABLE_STRINGS.COMBINED_PLEASE_SELECT_PLANT]: 'Please select',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE]: 'Sowing rate',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE_SINGLE]: 'Sowing rate - single',
    [SELECTABLE_STRINGS.COMBINED_PARTICIPATION_PERCENT]: 'Participation (%)',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE_MIX]: 'Sowing rate - in mixture',
    [SELECTABLE_STRINGS.COMBINED_SEED_PRICE_PER_ACRE]: 'Seed price per acre/BGN',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE_BY_PLANT_TYPE]: 'Sowing rate by plant type',
    [SELECTABLE_STRINGS.COMBINED_PARTICIPATION_DISTRIBUTION]: 'Participation distribution',
    [SELECTABLE_STRINGS.COMBINED_PRICE_PER_ACRE_COMPARISON]: 'Price per acre comparison',
    [SELECTABLE_STRINGS.COMBINED_PRICE_PER_ACRE_COMPARISON_LABEL]: 'Seed price per acre/BGN',
    [SELECTABLE_STRINGS.COMBINED_PRICE_PER_HECTARE_COMPARISON]: 'Price per hectare comparison',
    [SELECTABLE_STRINGS.COMBINED_PRICE_PER_HECTARE_COMPARISON_LABEL]: 'Seed price per hectare/BGN',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE_COMPARISON]: 'Sowing rate comparison',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE_SINGLE_PLANT]: 'Sowing rate - single',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE_MIX_PLANT]: 'Sowing rate - in mixture',
  },
};

export default LangMap;
