import { LangMapInterface } from './interfaces';

export enum SELECTABLE_STRINGS {
  //general
  GET_STARTED = 'GET_STARTED',
  HEADER_WELCOME = 'HEADER_WELCOME',
  MENU = 'MENU',
  HOME = 'HOME',
  REGISTER = 'REGISTER',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  OR = 'OR',
  PROFILE = 'PROFILE',
  NEED_HELP_Q = 'NEED_HELP_Q',
  HAS_VALUE_OUTSIDE_SUGGESTED_RANGE = 'HAS_VALUE_OUTSIDE_SUGGESTED_RANGE',
  SAVE_CALCULATION = 'SAVE_CALCULATION',
  CALCULATION_VISUALIZATION = 'CALCULATION_VISUALIZATION',
  LOADING = 'LOADING',
  HISTORY_HERE = 'HISTORY_HERE',
  NO_HISTORY = 'NO_HISTORY',
  NO_HISTORY_SOWING_RATE = 'NO_HISTORY_SOWING_RATE',
  NO_HISTORY_SEEDING_DATA = 'NO_HISTORY_SEEDING_DATA',
  SEARCH_PLACEHOLDER = 'SEARCH_PLACEHOLDER',
  SELECT_DATE = 'SELECT_DATE',

  HOME_PAGE_YOUR_TRUSTED_AGRO_CALCS = 'HOME_PAGE_YOUR_TRUSTED_AGRO_CALCS',
  HOME_PAGE_PRECISION_FARMING = 'HOME_PAGE_PRECISION_FARMING',
  HOME_PAGE_PRECISION_FARMING_DESCRIPTION = 'HOME_PAGE_PRECISION_FARMING_DESCRIPTION',
  HOME_PAGE_TIME_SAVING = 'HOME_PAGE_TIME_SAVING',
  HOME_PAGE_TIME_SAVING_DESCRIPTION = 'HOME_PAGE_TIME_SAVING_DESCRIPTION',
  HOME_PAGE_EXPERT_RECOMMENDATIONS = 'HOME_PAGE_EXPERT_RECOMMENDATIONS',
  HOME_PAGE_EXPERT_RECOMMENDATIONS_DESCRIPTION = 'HOME_PAGE_EXPERT_RECOMMENDATIONS_DESCRIPTION',
  HOME_PAGE_WHY_USE_AGRO_CALC = 'HOME_PAGE_WHY_USE_AGRO_CALC',
  HOME_PAGE_MODERN_FARMING_SOLUTIONS = 'HOME_PAGE_MODERN_FARMING_SOLUTIONS',
  HOME_PAGE_MODERN_FARMING_SOLUTIONS_DESCRIPTION = 'HOME_PAGE_MODERN_FARMING_SOLUTIONS_DESCRIPTION',
  HOME_PAGE_OUR_SUITE_OF_CALCULATORS = 'HOME_PAGE_OUR_SUITE_OF_CALCULATORS',

  //auth
  EMAIL = 'EMAIL',
  PASSWORD = 'PASSWORD',
  PASSWORD_CONFIRM = 'PASSWORD_CONFIRM',
  SUBMIT = 'SUBMIT',
  NO_ACC_Q = 'NO_ACC_Q',
  HAVE_ACC_Q = 'HAVE_ACC_Q',

  INVALID_EMAIL = 'INVALID_EMAIL',
  PASSWORD_MIN = 'PASSWORD_MIN',
  PASSWORD_HAS_LOWER = 'PASSWORD_HAS_LOWER',
  PASSWORD_HAS_UPPER = 'PASSWORD_HAS_UPPER',
  PASSWORD_HAS_NUMBER = 'PASSWORD_HAS_NUMBER',
  PASSWORD_HAS_SYMBOL = 'PASSWORD_HAS_SYMBOL',
  PASSWORDS_DONT_MATCH = 'PASSWORDS_DONT_MATCH',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  REQUEST_PASSWORD_RESET = 'REQUEST_PASSWORD_RESET',
  RESET_PASSWORD = 'RESET_PASSWORD',

  //info
  TOAST_ERROR = 'TOAST_ERROR',
  TOAST_ERROR_SESSION_EXPIRED = 'TOAST_ERROR_SESSION_EXPIRED',
  TOAST_ERROR_LOADING_DATA = 'TOAST_ERROR_LOADING_DATA',
  TOAST_ERROR_NOT_LOGGED_IN = 'TOAST_ERROR_NOT_LOGGED_IN',
  TOAST_ERROR_NO_PLANT_SELECTED = 'TOAST_ERROR_NO_PLANT_SELECTED',
  TOAST_SAVE_SUCCESS = 'TOAST_SAVE_SUCCESS',
  TOAST_REGISTER_SUCCESS = 'TOAST_REGISTER_SUCCESS',
  TOAST_LOGIN_SUCCESS = 'TOAST_LOGIN_SUCCESS',
  TOAST_LOGOUT_SUCCESS = 'TOAST_LOGOUT_SUCCESS',
  TOAST_TRY_AGAIN_LATER = 'TOAST_TRY_AGAIN_LATER',
  TOAST_PASSWORD_RESET_REQUEST_PROCESSING = 'TOAST_PASSWORD_RESET_REQUEST_PROCESSING',
  TOAST_PASSWORD_RESET_REQUEST_SENT = 'TOAST_PASSWORD_RESET_REQUEST_SENT',
  TOAST_ERROR_PASSWORD_RESET_REQUEST_FAILED = 'TOAST_ERROR_PASSWORD_RESET_REQUEST_FAILED',
  TOAST_PASSWORD_RESET_SUCCESS = 'TOAST_PASSWORD_RESET_SUCCESS',
  TOAST_ERROR_PASSWORD_RESET_FAILED = 'TOAST_ERROR_PASSWORD_RESET_FAILED',

  AGRICULTURAL_CALCULATORS = 'AGRICULTURAL_CALCULATORS',
  SELECT_CALCULATOR = 'SELECT_CALCULATOR',
  OPEN_CALCULATOR = 'OPEN_CALCULATOR',

  //settings
  SETTINGS = 'SETTINGS',
  SETTINGS_PREF_UNIT_OF_MEASUREMENT = 'SETTINGS_PREF_UNIT_OF_MEASUREMENT',
  SETTINGS_THEME = 'SETTINGS_THEME',
  SETTINGS_LANGUAGE = 'SETTINGS_LANGUAGE',
  SETTINGS_PREF_UNIT_OF_MEASUREMENT_ACRES = 'SETTINGS_PREF_UNIT_OF_MEASUREMENT_ACRES',
  SETTINGS_PREF_UNIT_OF_MEASUREMENT_ACRES_SYMBOL = 'SETTINGS_PREF_UNIT_OF_MEASUREMENT_ACRES_SYMBOL',
  SETTINGS_PREF_UNIT_OF_MEASUREMENT_HECTARES = 'SETTINGS_PREF_UNIT_OF_MEASUREMENT_HECTARES',
  SETTINGS_PREF_UNIT_OF_MEASUREMENT_HECTARES_SYMBOL = 'SETTINGS_PREF_UNIT_OF_MEASUREMENT_HECTARES_SYMBOL',

  //settings themes
  THEME_LIGHT = 'light',
  THEME_DARK = 'dark',
  THEME_SYSTEM = 'system',

  //general helpful
  G_LITER = 'G_LITER',
  G_KG = 'G_KG',
  ML_ACRE = 'ML_ACRE',
  G_ACRE = 'G_ACRE',
  G_100_KG_SEEDS = 'G_100_KG_SEEDS',

  //latin names
  // Seeding crops
  PISUM_SATIVUM = 'Pisum sativum', // Грах (Pea)
  GLYCINE_MAX = 'Glycine max', // Соя (Soybean)
  SORGHUM_VULGARE_VAR_TEHNICUM = 'Sorghum vulgare var. tehnicum', // Сорго (Sorghum)
  ZEA_MAYS = 'Zea mays', // Царевица (Corn)

  // Legumes (бобови)
  MEDICAGO_SATIVA = 'Medicago sativa', // Люцерна (Alfalfa)
  TRIFOLIUM_STELLATUM = 'Trifolium stellatum', // Звездан (Star Clover)
  TRIFOLIUM_PRATENSE = 'Trifolium pratense', // Червена детелина (Red Clover)
  TRIFOLIUM_REPENS = 'Trifolium repens', // Бяла детелина (White Clover)

  // Cereals / Grasses (зърнени / треви)
  LOLIUM_PERENNE = 'Lolium perenne', // Пасищен райграс (Perennial Ryegrass)
  AGROPYRON_CRISTATUM = 'Agropyron cristatum', // Гребенчат житняк (Crested Wheatgrass)
  DACTYLIS_GLOMERATA = 'Dactylis glomerata', // Ежова главица (Orchard Grass)
  AVENULA_PUBESCENS = 'Avenula pubescens', // Безосилеста овсига (Downy Oatgrass)
  FESTUCA_PRATENSIS = 'Festuca pratensis', // Ливадна власатка (Meadow Fescue)
  FESTUCA_RUBRA = 'Festuca rubra', // Червена власатка (Red Fescue)

  //sowing
  SOWING_RATE_CALC_TITLE = 'SOWING_RATE_CALC_TITLE',
  SOWING_RATE_CALC_DESCRIPTION = 'SOWING_RATE_CALC_DESCRIPTION',
  SOWING_RATE_PICK_CULTURE = 'SOWING_RATE_PICK_CULTURE',
  SOWING_RATE_SELECTED_CULTURE = 'SOWING_RATE_SELECTED_CULTURE',
  SOWING_RATE_INPUT_SUGGESTED_RANGE = 'SOWING_RATE_INPUT_SUGGESTED_RANGE',
  SOWING_RATE_INPUT_SUGGESTED_VALUE = 'SOWING_RATE_INPUT_SUGGESTED_VALUE',
  SOWING_RATE_INPUT_COEFFICIENT_SECURITY = 'SOWING_RATE_INPUT_COEFFICIENT_SECURITY',
  SOWING_RATE_INPUT_WANTED_PLANTS_PER_M2 = 'SOWING_RATE_INPUT_WANTED_PLANTS_PER_M2',
  SOWING_RATE_INPUT_MASS_PER_1000g_SEEDS = 'SOWING_RATE_INPUT_MASS_PER_1000g_SEEDS',
  SOWING_RATE_INPUT_PURITY = 'SOWING_RATE_INPUT_PURITY',
  SOWING_RATE_INPUT_GERMINATION = 'SOWING_RATE_INPUT_GERMINATION',
  SOWING_RATE_INPUT_ROW_SPACING = 'SOWING_RATE_INPUT_ROW_SPACING',
  SOWING_RATE_INPUT_TOTAL_AREA = 'SOWING_RATE_INPUT_TOTAL_AREA',
  SOWING_RATE_OUTPUT_SOWING_RATE = 'SOWING_RATE_OUTPUT_SOWING_RATE',
  SOWING_RATE_OUTPUT_SOWING_RATE_SEEDS_PER_M2 = 'SOWING_RATE_OUTPUT_SOWING_RATE_SEEDS_PER_M2',
  SOWING_RATE_OUTPUT_SOWING_RATE_PLANTS_PER_ACRE = 'SOWING_RATE_OUTPUT_SOWING_RATE_PLANTS_PER_ACRE',
  SOWING_RATE_OUTPUT_SOWING_RATE_PLANTS_PER_HECTARE = 'SOWING_RATE_OUTPUT_SOWING_RATE_PLANTS_PER_HECTARE',
  SOWING_RATE_OUTPUT_USED_SEEDS = 'SOWING_RATE_OUTPUT_USED_SEEDS',
  SOWING_RATE_OUTPUT_KA_PER_ACRE = 'SOWING_RATE_OUTPUT_KA_PER_ACRE',
  SOWING_RATE_OUTPUT_KA_PER_HECTARE = 'SOWING_RATE_OUTPUT_KA_PER_HECTARE',
  SOWING_RATE_OUTPUT_ROW_SPACING = 'SOWING_RATE_OUTPUT_ROW_SPACING',
  SOWING_RATE_OUTPUT_ROW_SPACING_CM = 'SOWING_RATE_OUTPUT_ROW_SPACING_CM',
  SOWING_RATE_THIS_IS_SUGGESTED = 'SOWING_RATE_THIS_IS_SUGGESTED',
  SOWING_RATE_VIZ = 'SOWING_RATE_VIZ',
  SOWING_RATE_VIZ_GENERAL = 'SOWING_RATE_VIZ_GENERAL',
  SOWING_RATE_VIZ_ALL_ELEMENTS = 'SOWING_RATE_VIZ_ALL_ELEMENTS',
  SOWING_RATE_VIZ_ELEMENTS_RELATIONSHIP = 'SOWING_RATE_VIZ_ELEMENTS_RELATIONSHIP',
  SOWING_RATE_VIZ_COMPARE_CALCED_PARAMS = 'SOWING_RATE_VIZ_COMPARE_CALC_PARAMS',
  SOWING_RATE_VIZ_COMPARE_CALCED_PARAMS_VECED = 'SOWING_RATE_VIZ_COMPARE_CALC_PARAMS_VECED',
  SOWING_RATE_VIZ_PLANTING_EFFICIENCY = 'SOWING_RATE_VIZ_PLANTING_EFFICIENCY',
  SOWING_RATE_VIZ_PLANTING_EFFICIENCY_SEEDS_TO_PLANTS = 'SOWING_RATE_VIZ_PLANTING_EFFICIENCY_SEEDS_TO_PLANTS',
  SOWING_RATE_VIZ_PLANTING_EFFICIENCY_COVERAGE = 'SOWING_RATE_VIZ_PLANTING_EFFICIENCY_COVERAGE',
  SOWING_RATE_VIZ_PLANTING_EFFICIENCY_DENSITY = 'SOWING_RATE_VIZ_PLANTING_EFFICIENCY_DENSITY',
  SOWING_RATE_VIZ_PLANTING_EFFICIENCY_EFFICIENCY = 'SOWING_RATE_VIZ_PLANTING_EFFICIENCY_EFFICIENCY',
  SOWING_RATE_VIZ_PLANTING_EFFICIENCY_SUGGESTED = 'SOWING_RATE_VIZ_PLANTING_EFFICIENCY_SUGGESTED',

  //sowing tour
  SOWING_RATE_TOUR_CULTURE_SELECT = 'SOWING_RATE_TOUR_CULTURE_SELECT',
  SOWING_RATE_TOUR_CULTURE_SELECT_DESCRIPTION_SELECT_CULTURE_FIRST = 'SOWING_RATE_TOUR_CULTURE_SELECT_DESCRIPTION_SELECT_CULTURE_FIRST',
  SOWING_RATE_TOUR_CULTURE_SELECT_DESCRIPTION = 'SOWING_RATE_TOUR_CULTURE_SELECT_DESCRIPTION',
  SOWING_RATE_TOUR_SAFETY_COEFFICIENT = 'SOWING_RATE_TOUR_SAFETY_COEFFICIENT',
  SOWING_RATE_TOUR_SAFETY_COEFFICIENT_DESCRIPTION = 'SOWING_RATE_TOUR_SAFETY_COEFFICIENT_DESCRIPTION',
  SOWING_RATE_TOUR_WANTED_PLANTS_PER_M2 = 'SOWING_RATE_TOUR_WANTED_PLANTS_PER_M2',
  SOWING_RATE_TOUR_WANTED_PLANTS_PER_M2_DESCRIPTION = 'SOWING_RATE_TOUR_WANTED_PLANTS_PER_M2_DESCRIPTION',
  SOWING_RATE_TOUR_MASS_PER_1000g = 'SOWING_RATE_TOUR_MASS_PER_1000g',
  SOWING_RATE_TOUR_MASS_PER_1000g_DESCRIPTION = 'SOWING_RATE_TOUR_MASS_PER_1000g_DESCRIPTION',
  SOWING_RATE_TOUR_PURITY = 'SOWING_RATE_TOUR_PURITY',
  SOWING_RATE_TOUR_PURITY_DESCRIPTION = 'SOWING_RATE_TOUR_PURITY_DESCRIPTION',
  SOWING_RATE_TOUR_GERMINATION = 'SOWING_RATE_TOUR_GERMINATION',
  SOWING_RATE_TOUR_GERMINATION_DESCRIPTION = 'SOWING_RATE_TOUR_GERMINATION_DESCRIPTION',
  SOWING_RATE_TOUR_ROW_SPACING = 'SOWING_RATE_TOUR_ROW_SPACING',
  SOWING_RATE_TOUR_ROW_SPACING_DESCRIPTION = 'SOWING_RATE_TOUR_ROW_SPACING_DESCRIPTION',
  SOWING_RATE_TOUR_VISUALIZATION = 'SOWING_RATE_TOUR_VISUALIZATION',
  SOWING_RATE_TOUR_VISUALIZATION_DESCRIPTION = 'SOWING_RATE_TOUR_VISUALIZATION_DESCRIPTION',
  SOWING_RATE_TOUR_TOTAL_AREA = 'SOWING_RATE_TOUR_TOTAL_AREA',
  SOWING_RATE_TOUR_TOTAL_AREA_DESCRIPTION = 'SOWING_RATE_TOUR_TOTAL_AREA_DESCRIPTION',
  SOWING_RATE_TOUR_SAVE_CALCULATION = 'SOWING_RATE_TOUR_SAVE_CALCULATION',
  SOWING_RATE_TOUR_SAVE_CALCULATION_DESCRIPTION = 'SOWING_RATE_TOUR_SAVE_CALCULATION_DESCRIPTION',
  SOWING_RATE_TOUR_ANALYSIS = 'SOWING_RATE_TOUR_ANALYSIS',
  SOWING_RATE_TOUR_ANALYSIS_DESCRIPTION = 'SOWING_RATE_TOUR_ANALYSIS_DESCRIPTION',

  //combined calculator
  COMBINED_CALC_TITLE = 'COMBINED_CALC_TITLE',
  COMBINED_CALC_DESCRIPTION = 'COMBINED_CALC_DESCRIPTION',
  COMBINED_LEGUME_TITLE = 'COMBINED_LEGUME_TITLE',
  COMBINED_CEREAL_TITLE = 'COMBINED_CEREAL_TITLE',
  COMBINED_SUMMARY_TITLE = 'COMBINED_SUMMARY_TITLE',
  COMBINED_TOTAL_PARTICIPATION = 'COMBINED_TOTAL_PARTICIPATION',
  COMBINED_FINAL_PRICE = 'COMBINED_FINAL_PRICE',
  COMBINED_VALUES_OUTSIDE_LIMIT = 'COMBINED_VALUES_OUTSIDE_LIMIT',
  COMBINED_SAVE_CALCULATION = 'COMBINED_SAVE_CALCULATION',
  COMBINED_VISUALIZATION_TITLE = 'COMBINED_VISUALIZATION_TITLE',
  COMBINED_VISUALIZATION_DESCRIPTION = 'COMBINED_VISUALIZATION_DESCRIPTION',
  COMBINED_TOTAL_PARTICIPATION_LABEL = 'COMBINED_TOTAL_PARTICIPATION_LABEL',
  COMBINED_MAX_PARTICIPATION = 'COMBINED_MAX_PARTICIPATION',
  COMBINED_ACTIVE = 'COMBINED_ACTIVE',
  COMBINED_PLEASE_SELECT_PLANT = 'COMBINED_PLEASE_SELECT_PLANT',
  COMBINED_PLANT = 'COMBINED_PLANT',
  COMBINED_SOWING_RATE = 'COMBINED_SOWING_RATE',
  COMBINED_SOWING_RATE_SINGLE = 'COMBINED_SOWING_RATE_SINGLE',
  COMBINED_PARTICIPATION_PERCENT = 'COMBINED_PARTICIPATION_PERCENT',
  COMBINED_SOWING_RATE_MIX = 'COMBINED_SOWING_RATE_MIX',
  COMBINED_SEED_PRICE_PER_ACRE = 'COMBINED_SEED_PRICE_PER_ACRE',
  COMBINED_SOWING_RATE_BY_PLANT_TYPE = 'COMBINED_SOWING_RATE_BY_PLANT_TYPE',
  COMBINED_PARTICIPATION_DISTRIBUTION = 'COMBINED_PARTICIPATION_DISTRIBUTION',
  COMBINED_PRICE_PER_ACRE_COMPARISON = 'COMBINED_PRICE_PER_ACRE_COMPARISON',
  COMBINED_PRICE_PER_ACRE_COMPARISON_LABEL = 'COMBINED_PRICE_PER_ACRE_COMPARISON_LABEL',
  COMBINED_PRICE_PER_HECTARE_COMPARISON = 'COMBINED_PRICE_PER_HECTARE_COMPARISON',
  COMBINED_PRICE_PER_HECTARE_COMPARISON_LABEL = 'COMBINED_PRICE_PER_HECTARE_COMPARISON_LABEL',
  COMBINED_SOWING_RATE_COMPARISON = 'COMBINED_SOWING_RATE_COMPARISON',
  COMBINED_SOWING_RATE_SINGLE_PLANT = 'COMBINED_SOWING_RATE_SINGLE_PLANT',
  COMBINED_SOWING_RATE_MIX_PLANT = 'COMBINED_SOWING_RATE_MIX_PLANT',

  COMBINED_TOUR_PERENNIAL_LEGUME = 'COMBINED_TOUR_PERENNIAL_LEGUME',
  COMBINED_TOUR_PERENNIAL_LEGUME_DESCRIPTION = 'COMBINED_TOUR_PERENNIAL_LEGUME_DESCRIPTION',
  COMBINED_TOUR_CROP_ACTIVATION = 'COMBINED_TOUR_CROP_ACTIVATION',
  COMBINED_TOUR_CROP_ACTIVATION_DESCRIPTION = 'COMBINED_TOUR_CROP_ACTIVATION_DESCRIPTION',
  COMBINED_TOUR_PLANT_SELECTION = 'COMBINED_TOUR_PLANT_SELECTION',
  COMBINED_TOUR_PLANT_SELECTION_DESCRIPTION = 'COMBINED_TOUR_PLANT_SELECTION_DESCRIPTION',
  COMBINED_TOUR_SOWING_RATE_SINGLE = 'COMBINED_TOUR_SOWING_RATE_SINGLE',
  COMBINED_TOUR_SOWING_RATE_SINGLE_DESCRIPTION = 'COMBINED_TOUR_SOWING_RATE_SINGLE_DESCRIPTION',
  COMBINED_TOUR_LEGUME_PARTICIPATION = 'COMBINED_TOUR_LEGUME_PARTICIPATION',
  COMBINED_TOUR_LEGUME_PARTICIPATION_DESCRIPTION = 'COMBINED_TOUR_LEGUME_PARTICIPATION_DESCRIPTION',
  COMBINED_TOUR_PARTICIPATION_PERCENT = 'COMBINED_TOUR_PARTICIPATION_PERCENT',
  COMBINED_TOUR_PARTICIPATION_PERCENT_DESCRIPTION = 'COMBINED_TOUR_PARTICIPATION_PERCENT_DESCRIPTION',
  COMBINED_TOUR_SOWING_RATE_MIXTURE = 'COMBINED_TOUR_SOWING_RATE_MIXTURE',
  COMBINED_TOUR_SOWING_RATE_MIXTURE_DESCRIPTION = 'COMBINED_TOUR_SOWING_RATE_MIXTURE_DESCRIPTION',
  COMBINED_TOUR_SEED_PRICE = 'COMBINED_TOUR_SEED_PRICE',
  COMBINED_TOUR_SEED_PRICE_DESCRIPTION = 'COMBINED_TOUR_SEED_PRICE_DESCRIPTION',
  COMBINED_TOUR_PERENNIAL_CEREAL = 'COMBINED_TOUR_PERENNIAL_CEREAL',
  COMBINED_TOUR_PERENNIAL_CEREAL_DESCRIPTION = 'COMBINED_TOUR_PERENNIAL_CEREAL_DESCRIPTION',
  COMBINED_TOUR_CEREAL_PARTICIPATION = 'COMBINED_TOUR_CEREAL_PARTICIPATION',
  COMBINED_TOUR_CEREAL_PARTICIPATION_DESCRIPTION = 'COMBINED_TOUR_CEREAL_PARTICIPATION_DESCRIPTION',
  COMBINED_TOUR_MIXTURE_SUMMARY = 'COMBINED_TOUR_MIXTURE_SUMMARY',
  COMBINED_TOUR_MIXTURE_SUMMARY_DESCRIPTION = 'COMBINED_TOUR_MIXTURE_SUMMARY_DESCRIPTION',
  COMBINED_TOUR_TOTAL_PARTICIPATION = 'COMBINED_TOUR_TOTAL_PARTICIPATION',
  COMBINED_TOUR_TOTAL_PARTICIPATION_DESCRIPTION = 'COMBINED_TOUR_TOTAL_PARTICIPATION_DESCRIPTION',
  COMBINED_TOUR_FINAL_PRICE = 'COMBINED_TOUR_FINAL_PRICE',
  COMBINED_TOUR_FINAL_PRICE_DESCRIPTION = 'COMBINED_TOUR_FINAL_PRICE_DESCRIPTION',
  COMBINED_TOUR_SAVE_CALCULATION = 'COMBINED_TOUR_SAVE_CALCULATION',
  COMBINED_TOUR_SAVE_CALCULATION_DESCRIPTION = 'COMBINED_TOUR_SAVE_CALCULATION_DESCRIPTION',
  COMBINED_TOUR_VISUALIZATION = 'COMBINED_TOUR_VISUALIZATION',
  COMBINED_TOUR_VISUALIZATION_DESCRIPTION = 'COMBINED_TOUR_VISUALIZATION_DESCRIPTION',

  //chemical protection
  CHEMICAL_PROTECTION_CALC_TITLE = 'CHEMICAL_PROTECTION_CALC_TITLE',
  CHEMICAL_PROTECTION_CALC_DESCRIPTION = 'CHEMICAL_PROTECTION_CALC_DESCRIPTION',
  CHEMICAL_PROTECTION_SELECT_CHEMICAL = 'CHEMICAL_PROTECTION_SELECT_CHEMICAL',

  CHEMICAL_PROTECTION_CHEMICAL_TYPE_HERBICIDE = 'HERBICIDE',
  CHEMICAL_PROTECTION_CHEMICAL_TYPE_INSECTICIDE = 'INSECTICIDE',
  CHEMICAL_PROTECTION_CHEMICAL_TYPE_FUNGICIDE = 'FUNGICIDE',

  CHEMICAL_PROTECTION_APPLICATION_STAGE_PRE_EMERGENT = 'PRE_EMERGENT',
  CHEMICAL_PROTECTION_APPLICATION_STAGE_PRE_EMERGENT_AFTER_SOWING_BEFORE_EMERGENCE = 'PRE_EMERGENT_AFTER_SOWING_BEFORE_EMERGENCE',
  CHEMICAL_PROTECTION_APPLICATION_STAGE_PRE_EMERGENT_BEFORE_START_OF_GROWING_SEASON = 'PRE_EMERGENT_BEFORE_START_OF_GROWING_SEASON',
  CHEMICAL_PROTECTION_APPLICATION_STAGE_PRE_EMERGENT_PRE_SOWING_SEEDS_TREATMENT = 'PRE_EMERGENT_PRE_SOWING_SEEDS_TREATMENT',
  CHEMICAL_PROTECTION_APPLICATION_STAGE_PRE_EMERGENT_DURING_SOWING = 'PRE_EMERGENT_DURING_SOWING',
  CHEMICAL_PROTECTION_APPLICATION_STAGE_POST_EMERGENT = 'POST_EMERGENT',

  //chemical protection chemicals
  CHEMICAL_PROTECTION_CHEM_DUAL_GOLD_960_EC = 'CHEMICAL_PROTECTION_CHEM_DUAL_GOLD_960_EC',
  CHEMICAL_PROTECTION_CHEM_DUAL_GOLD_960_EC_INFO = 'CHEMICAL_PROTECTION_CHEM_DUAL_GOLD_960_EC_INFO',
  CHEMICAL_PROTECTION_CHEM_DUAL_GOLD_960_EC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_DUAL_GOLD_960_EC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_EKLIPS_70_VDG = 'CHEMICAL_PROTECTION_CHEM_EKLIPS_70_VDG',
  CHEMICAL_PROTECTION_CHEM_EKLIPS_70_VDG_INFO = 'CHEMICAL_PROTECTION_CHEM_EKLIPS_70_VDG_INFO',
  CHEMICAL_PROTECTION_CHEM_EKLIPS_70_VDG_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_EKLIPS_70_VDG_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_LEOPARD_5_EC = 'CHEMICAL_PROTECTION_CHEM_LEOPARD_5_EC',
  CHEMICAL_PROTECTION_CHEM_LEOPARD_5_EC_INFO = 'CHEMICAL_PROTECTION_CHEM_LEOPARD_5_EC_INFO',
  CHEMICAL_PROTECTION_CHEM_LEOPARD_5_EC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_LEOPARD_5_EC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_LENTAGRAN_45_WP = 'CHEMICAL_PROTECTION_CHEM_LENTAGRAN_45_WP',
  CHEMICAL_PROTECTION_CHEM_LENTAGRAN_45_WP_INFO = 'CHEMICAL_PROTECTION_CHEM_LENTAGRAN_45_WP_INFO',
  CHEMICAL_PROTECTION_CHEM_LENTAGRAN_45_WP_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_LENTAGRAN_45_WP_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_PULSAR_40_SL = 'CHEMICAL_PROTECTION_CHEM_PULSAR_40_SL',
  CHEMICAL_PROTECTION_CHEM_PULSAR_40_SL_INFO = 'CHEMICAL_PROTECTION_CHEM_PULSAR_40_SL_INFO',
  CHEMICAL_PROTECTION_CHEM_PULSAR_40_SL_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_PULSAR_40_SL_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_DECIS_100_EC = 'CHEMICAL_PROTECTION_CHEM_DECIS_100_EC',
  CHEMICAL_PROTECTION_CHEM_DECIS_100_EC_INFO = 'CHEMICAL_PROTECTION_CHEM_DECIS_100_EC_INFO',
  CHEMICAL_PROTECTION_CHEM_DECIS_100_EC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_DECIS_100_EC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_LAMDEX_EXTRA = 'CHEMICAL_PROTECTION_CHEM_LAMDEX_EXTRA',
  CHEMICAL_PROTECTION_CHEM_LAMDEX_EXTRA_INFO = 'CHEMICAL_PROTECTION_CHEM_LAMDEX_EXTRA_INFO',
  CHEMICAL_PROTECTION_CHEM_LAMDEX_EXTRA_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_LAMDEX_EXTRA_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_METEOR = 'CHEMICAL_PROTECTION_CHEM_METEOR',
  CHEMICAL_PROTECTION_CHEM_METEOR_INFO = 'CHEMICAL_PROTECTION_CHEM_METEOR_INFO',
  CHEMICAL_PROTECTION_CHEM_METEOR_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_METEOR_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_SUMI_ALPHA_5_EC = 'CHEMICAL_PROTECTION_CHEM_SUMI_ALPHA_5_EC',
  CHEMICAL_PROTECTION_CHEM_SUMI_ALPHA_5_EC_INFO = 'CHEMICAL_PROTECTION_CHEM_SUMI_ALPHA_5_EC_INFO',
  CHEMICAL_PROTECTION_CHEM_SUMI_ALPHA_5_EC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_SUMI_ALPHA_5_EC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_MOSPILAN_20_SG = 'CHEMICAL_PROTECTION_CHEM_MOSPILAN_20_SG',
  CHEMICAL_PROTECTION_CHEM_MOSPILAN_20_SG_INFO = 'CHEMICAL_PROTECTION_CHEM_MOSPILAN_20_SG_INFO',
  CHEMICAL_PROTECTION_CHEM_MOSPILAN_20_SG_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_MOSPILAN_20_SG_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_STOMP_AQUA = 'CHEMICAL_PROTECTION_CHEM_STOMP_AQUA',
  CHEMICAL_PROTECTION_CHEM_STOMP_AQUA_INFO = 'CHEMICAL_PROTECTION_CHEM_STOMP_AQUA_INFO',
  CHEMICAL_PROTECTION_CHEM_STOMP_AQUA_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_STOMP_AQUA_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_CHALLENGE_600_SC = 'CHEMICAL_PROTECTION_CHEM_CHALLENGE_600_SC',
  CHEMICAL_PROTECTION_CHEM_CHALLENGE_600_SC_INFO = 'CHEMICAL_PROTECTION_CHEM_CHALLENGE_600_SC_INFO',
  CHEMICAL_PROTECTION_CHEM_CHALLENGE_600_SC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_CHALLENGE_600_SC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_STRATOS_ULTRA = 'CHEMICAL_PROTECTION_CHEM_STRATOS_ULTRA',
  CHEMICAL_PROTECTION_CHEM_STRATOS_ULTRA_INFO = 'CHEMICAL_PROTECTION_CHEM_STRATOS_ULTRA_INFO',
  CHEMICAL_PROTECTION_CHEM_STRATOS_ULTRA_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_STRATOS_ULTRA_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_ACHIBA_MAX = 'CHEMICAL_PROTECTION_CHEM_ACHIBA_MAX',
  CHEMICAL_PROTECTION_CHEM_ACHIBA_MAX_INFO = 'CHEMICAL_PROTECTION_CHEM_ACHIBA_MAX_INFO',
  CHEMICAL_PROTECTION_CHEM_ACHIBA_MAX_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_ACHIBA_MAX_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_CORUM = 'CHEMICAL_PROTECTION_CHEM_CORUM',
  CHEMICAL_PROTECTION_CHEM_CORUM_INFO = 'CHEMICAL_PROTECTION_CHEM_CORUM_INFO',
  CHEMICAL_PROTECTION_CHEM_CORUM_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_CORUM_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_LEBRON_0_5_G = 'CHEMICAL_PROTECTION_CHEM_LEBRON_0_5_G',
  CHEMICAL_PROTECTION_CHEM_LEBRON_0_5_G_INFO = 'CHEMICAL_PROTECTION_CHEM_LEBRON_0_5_G_INFO',
  CHEMICAL_PROTECTION_CHEM_LEBRON_0_5_G_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_LEBRON_0_5_G_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_OASIS_5_EC = 'CHEMICAL_PROTECTION_CHEM_OASIS_5_EC',
  CHEMICAL_PROTECTION_CHEM_OASIS_5_EC_INFO = 'CHEMICAL_PROTECTION_CHEM_OASIS_5_EC_INFO',
  CHEMICAL_PROTECTION_CHEM_OASIS_5_EC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_OASIS_5_EC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_CITRINE_MAX = 'CHEMICAL_PROTECTION_CHEM_CITRINE_MAX',
  CHEMICAL_PROTECTION_CHEM_CITRINE_MAX_INFO = 'CHEMICAL_PROTECTION_CHEM_CITRINE_MAX_INFO',
  CHEMICAL_PROTECTION_CHEM_CITRINE_MAX_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_CITRINE_MAX_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_FLIPPER = 'CHEMICAL_PROTECTION_CHEM_FLIPPER',
  CHEMICAL_PROTECTION_CHEM_FLIPPER_INFO = 'CHEMICAL_PROTECTION_CHEM_FLIPPER_INFO',
  CHEMICAL_PROTECTION_CHEM_FLIPPER_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_FLIPPER_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_ORTIVA_TOP_SC = 'CHEMICAL_PROTECTION_CHEM_ORTIVA_TOP_SC',
  CHEMICAL_PROTECTION_CHEM_ORTIVA_TOP_SC_INFO = 'CHEMICAL_PROTECTION_CHEM_ORTIVA_TOP_SC_INFO',
  CHEMICAL_PROTECTION_CHEM_ORTIVA_TOP_SC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_ORTIVA_TOP_SC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_SWITCH_625_WG = 'CHEMICAL_PROTECTION_CHEM_SWITCH_625_WG',
  CHEMICAL_PROTECTION_CHEM_SWITCH_625_WG_INFO = 'CHEMICAL_PROTECTION_CHEM_SWITCH_625_WG_INFO',
  CHEMICAL_PROTECTION_CHEM_SWITCH_625_WG_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_SWITCH_625_WG_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_BORDEAUX_MIX_20_VP = 'CHEMICAL_PROTECTION_CHEM_BORDEAUX_MIX_20_VP',
  CHEMICAL_PROTECTION_CHEM_BORDEAUX_MIX_20_VP_INFO = 'CHEMICAL_PROTECTION_CHEM_BORDEAUX_MIX_20_VP_INFO',
  CHEMICAL_PROTECTION_CHEM_BORDEAUX_MIX_20_VP_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_BORDEAUX_MIX_20_VP_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_SULPHUR_WG = 'CHEMICAL_PROTECTION_CHEM_SULPHUR_WG',
  CHEMICAL_PROTECTION_CHEM_SULPHUR_WG_INFO = 'CHEMICAL_PROTECTION_CHEM_SULPHUR_WG_INFO',
  CHEMICAL_PROTECTION_CHEM_SULPHUR_WG_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_SULPHUR_WG_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_ZOXIS_250_SC = 'CHEMICAL_PROTECTION_CHEM_ZOXIS_250_SC',
  CHEMICAL_PROTECTION_CHEM_ZOXIS_250_SC_INFO = 'CHEMICAL_PROTECTION_CHEM_ZOXIS_250_SC_INFO',
  CHEMICAL_PROTECTION_CHEM_ZOXIS_250_SC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_ZOXIS_250_SC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_SIRTAKI = 'CHEMICAL_PROTECTION_CHEM_SIRTAKI',
  CHEMICAL_PROTECTION_CHEM_SIRTAKI_INFO = 'CHEMICAL_PROTECTION_CHEM_SIRTAKI_INFO',
  CHEMICAL_PROTECTION_CHEM_SIRTAKI_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_SIRTAKI_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_SALTUS = 'CHEMICAL_PROTECTION_CHEM_SALTUS',
  CHEMICAL_PROTECTION_CHEM_SALTUS_INFO = 'CHEMICAL_PROTECTION_CHEM_SALTUS_INFO',
  CHEMICAL_PROTECTION_CHEM_SALTUS_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_SALTUS_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_PANTHER_40_EC = 'CHEMICAL_PROTECTION_CHEM_PANTHER_40_EC',
  CHEMICAL_PROTECTION_CHEM_PANTHER_40_EC_INFO = 'CHEMICAL_PROTECTION_CHEM_PANTHER_40_EC_INFO',
  CHEMICAL_PROTECTION_CHEM_PANTHER_40_EC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_PANTHER_40_EC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_DECA_EC = 'CHEMICAL_PROTECTION_CHEM_DECA_EC',
  CHEMICAL_PROTECTION_CHEM_DECA_EC_INFO = 'CHEMICAL_PROTECTION_CHEM_DECA_EC_INFO',
  CHEMICAL_PROTECTION_CHEM_DECA_EC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_DECA_EC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_TRIKA_EXPERT = 'CHEMICAL_PROTECTION_CHEM_TRIKA_EXPERT',
  CHEMICAL_PROTECTION_CHEM_TRIKA_EXPERT_INFO = 'CHEMICAL_PROTECTION_CHEM_TRIKA_EXPERT_INFO',
  CHEMICAL_PROTECTION_CHEM_TRIKA_EXPERT_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_TRIKA_EXPERT_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_RETENGO_20_EC = 'CHEMICAL_PROTECTION_CHEM_RETENGO_20_EC',
  CHEMICAL_PROTECTION_CHEM_RETENGO_20_EC_INFO = 'CHEMICAL_PROTECTION_CHEM_RETENGO_20_EC_INFO',
  CHEMICAL_PROTECTION_CHEM_RETENGO_20_EC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_RETENGO_20_EC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_DIFKOR_250_SC = 'CHEMICAL_PROTECTION_CHEM_DIFKOR_250_SC',
  CHEMICAL_PROTECTION_CHEM_DIFKOR_250_SC_INFO = 'CHEMICAL_PROTECTION_CHEM_DIFKOR_250_SC_INFO',
  CHEMICAL_PROTECTION_CHEM_DIFKOR_250_SC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_DIFKOR_250_SC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_AGROXONE_500_SL = 'CHEMICAL_PROTECTION_CHEM_AGROXONE_500_SL',
  CHEMICAL_PROTECTION_CHEM_AGROXONE_500_SL_INFO = 'CHEMICAL_PROTECTION_CHEM_AGROXONE_500_SL_INFO',
  CHEMICAL_PROTECTION_CHEM_AGROXONE_500_SL_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_AGROXONE_500_SL_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_GENERO_480_SL = 'CHEMICAL_PROTECTION_CHEM_GENERO_480_SL',
  CHEMICAL_PROTECTION_CHEM_GENERO_480_SL_INFO = 'CHEMICAL_PROTECTION_CHEM_GENERO_480_SL_INFO',
  CHEMICAL_PROTECTION_CHEM_GENERO_480_SL_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_GENERO_480_SL_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_KIDEKA_PRO = 'CHEMICAL_PROTECTION_CHEM_KIDEKA_PRO',
  CHEMICAL_PROTECTION_CHEM_KIDEKA_PRO_INFO = 'CHEMICAL_PROTECTION_CHEM_KIDEKA_PRO_INFO',
  CHEMICAL_PROTECTION_CHEM_KIDEKA_PRO_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_KIDEKA_PRO_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_COLOMBO_PRO = 'CHEMICAL_PROTECTION_CHEM_COLOMBO_PRO',
  CHEMICAL_PROTECTION_CHEM_COLOMBO_PRO_INFO = 'CHEMICAL_PROTECTION_CHEM_COLOMBO_PRO_INFO',
  CHEMICAL_PROTECTION_CHEM_COLOMBO_PRO_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_COLOMBO_PRO_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_SIVANTO_ENERGY = 'CHEMICAL_PROTECTION_CHEM_SIVANTO_ENERGY',
  CHEMICAL_PROTECTION_CHEM_SIVANTO_ENERGY_INFO = 'CHEMICAL_PROTECTION_CHEM_SIVANTO_ENERGY_INFO',
  CHEMICAL_PROTECTION_CHEM_SIVANTO_ENERGY_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_SIVANTO_ENERGY_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_BISMARCK_KS = 'CHEMICAL_PROTECTION_CHEM_BISMARCK_KS',
  CHEMICAL_PROTECTION_CHEM_BISMARCK_KS_INFO = 'CHEMICAL_PROTECTION_CHEM_BISMARCK_KS_INFO',
  CHEMICAL_PROTECTION_CHEM_BISMARCK_KS_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_BISMARCK_KS_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_ARRAT = 'CHEMICAL_PROTECTION_CHEM_ARRAT',
  CHEMICAL_PROTECTION_CHEM_ARRAT_INFO = 'CHEMICAL_PROTECTION_CHEM_ARRAT_INFO',
  CHEMICAL_PROTECTION_CHEM_ARRAT_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_ARRAT_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_AMINOPIELIK_600_SL = 'CHEMICAL_PROTECTION_CHEM_AMINOPIELIK_600_SL',
  CHEMICAL_PROTECTION_CHEM_AMINOPIELIK_600_SL_INFO = 'CHEMICAL_PROTECTION_CHEM_AMINOPIELIK_600_SL_INFO',
  CHEMICAL_PROTECTION_CHEM_AMINOPIELIK_600_SL_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_AMINOPIELIK_600_SL_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_JANERO_480_SL = 'CHEMICAL_PROTECTION_CHEM_JANERO_480_SL',
  CHEMICAL_PROTECTION_CHEM_JANERO_480_SL_INFO = 'CHEMICAL_PROTECTION_CHEM_JANERO_480_SL_INFO',
  CHEMICAL_PROTECTION_CHEM_JANERO_480_SL_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_JANERO_480_SL_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_CORAGEN_20_SC = 'CHEMICAL_PROTECTION_CHEM_CORAGEN_20_SC',
  CHEMICAL_PROTECTION_CHEM_CORAGEN_20_SC_INFO = 'CHEMICAL_PROTECTION_CHEM_CORAGEN_20_SC_INFO',
  CHEMICAL_PROTECTION_CHEM_CORAGEN_20_SC_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_CORAGEN_20_SC_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_K_OBIOL_6_ULV = 'CHEMICAL_PROTECTION_CHEM_K_OBIOL_6_ULV',
  CHEMICAL_PROTECTION_CHEM_K_OBIOL_6_ULV_INFO = 'CHEMICAL_PROTECTION_CHEM_K_OBIOL_6_ULV_INFO',
  CHEMICAL_PROTECTION_CHEM_K_OBIOL_6_ULV_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_K_OBIOL_6_ULV_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_INAZUMA = 'CHEMICAL_PROTECTION_CHEM_INAZUMA',
  CHEMICAL_PROTECTION_CHEM_INAZUMA_INFO = 'CHEMICAL_PROTECTION_CHEM_INAZUMA_INFO',
  CHEMICAL_PROTECTION_CHEM_INAZUMA_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_INAZUMA_INFO_NOTES',
  CHEMICAL_PROTECTION_CHEM_REDIGO_M = 'CHEMICAL_PROTECTION_CHEM_REDIGO_M',
  CHEMICAL_PROTECTION_CHEM_REDIGO_M_INFO = 'CHEMICAL_PROTECTION_CHEM_REDIGO_M_INFO',
  CHEMICAL_PROTECTION_CHEM_REDIGO_M_INFO_NOTES = 'CHEMICAL_PROTECTION_CHEM_REDIGO_M_INFO_NOTES',

  //chemcial active ingredients
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENTS = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENTS',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_S_METOLACHLOR = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_S_METOLACHLOR',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_METRIBUZIN = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_METRIBUZIN',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_QUIZALOFOP_P_ETHYL = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_QUIZALOFOP_P_ETHYL',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PYRIDATE = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PYRIDATE',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_IMAZAMOX = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_IMAZAMOX',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_DELTAMETHRIN = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_DELTAMETHRIN',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_LAMBDA_CYHALOTHRIN = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_LAMBDA_CYHALOTHRIN',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_ESFENVALERATE = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_ESFENVALERATE',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_ACETAMIPRID = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_ACETAMIPRID',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PENDIMETHALIN = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PENDIMETHALIN',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_ACLONIFEN = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_ACLONIFEN',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_CYCLOXYDIM = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_CYCLOXYDIM',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_BENTAZONE = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_BENTAZONE',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_TEFLUTHRIN = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_TEFLUTHRIN',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_FATTY_ACIDS = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_FATTY_ACIDS',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_AZOXYSTROBIN = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_AZOXYSTROBIN',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_DIFENOCONAZOLE = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_DIFENOCONAZOLE',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_FLUDIOXONIL = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_FLUDIOXONIL',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_CYPRODINIL = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_CYPRODINIL',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_BORDEAUX_MIXTURE = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_BORDEAUX_MIXTURE',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_SULFUR = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_SULFUR',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_CLOMAZONE = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_CLOMAZONE',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_QUIZALOFOP_P_TEFRIL = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_QUIZALOFOP_P_TEFRIL',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PYRACLOSTROBIN = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PYRACLOSTROBIN',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_MCPA = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_MCPA',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_DICAMBA = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_DICAMBA',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_MESOTRIONE = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_MESOTRIONE',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_CYPERMETHRIN = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_CYPERMETHRIN',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_FLUPYRADIFURON = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_FLUPYRADIFURON',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_TRITOSULFURON = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_TRITOSULFURON',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_2_4D_AMINE_SALT = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_2_4D_AMINE_SALT',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_RYNAXYPYR = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_RYNAXYPYR',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PROTHIOCONAZOLE = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PROTHIOCONAZOLE',
  CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_METALAXYL = 'CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_METALAXYL',

  //chemical protection enemies
  CHEMICAL_PROTECTION_ENEMY_TARGETS = 'CHEMICAL_PROTECTION_ENEMY_TARGETS',
  // chemical protection enemy targets
  // Балур (johnsongras)
  SORGHUM_HALEPENSE = 'Sorghum halepense',
  // Кисела трева (false nutsedge)
  CYPERUS_STRIGOSUS = 'Cyperus strigosus',
  // Кокоше просо (barnyard grass)
  ECHINOCHLOA_CRUS_GALLI = 'Echinochloa crus-galli',
  // Кръвно просо (hairy crabgrass)
  DIGITARIA_SANGUINALIS = 'Digitaria sanguinalis',
  // Кощрява (setaria)
  SETARIA_SPP = 'Setaria spp.',
  // Метлица (apera)
  APERA_SPР = 'Apera spр.',
  // Овчарска торбичка (shepherd's purse)
  CAPSELLA_BURSA_PASTORIS = 'Capsella bursa-pastoris',
  // Тученица (pursley)
  PORTULACA_OLERACEA = 'Portulaca oleracea',
  // Черно куче грозде (black nightshade)
  SOLANUM_NIGRUM = 'Solanum nigrum',
  // Щир (amaranths)
  AMARANTHUS = 'Amaranthus',
  // Лисича опашка (slender meadow foxtail)
  ALOPECURUS_MYOSUROIDES = 'Alopecurus myosuroides',
  // Райграс (ryegrass)
  LOLIUM = 'Lolium',
  // Червена мъртва коприва (redroot pigweed)
  AMARANTHUS_RETROFLEXUS = 'Amaranthus retroflexus',
  // Лобода (lamb's quarters)
  CHENOPODIUM_ALBUM = 'Chenopodium album',
  // Водно пипериче (water pepper)
  PERSICARIA_HYDROPIPER = 'Persicaria hydropiper',
  // Великденче (gypsyweed)
  VERONICA_OFFICINALIS = 'Veronica officinalis',
  // Врабчови чревца (chickweed)
  STELLARIA_MEDIA = 'Stellaria media',
  // Лайка (matricaria)
  MATRICARIA_RECUTITA = 'Matricaria recutita',
  // Дива ряпа (wild radish)
  RAPHANUS_RAPHANISTRUM = 'Raphanus raphanistrum',
  // Типове здравец (geranium)
  GERANIUM_SP = 'Geranium sp.',
  // Спореж (groundsel)
  SENECIO_VULGARIS = 'Senecio vulgaris',
  // Червена мъртва коприва (purple archangel)
  LAMIUM_PURPUREUM = 'Lamium purpureum',
  // Синап (field mustard)
  SINAPIS_ARVENSIS = 'Sinapis arvensis',
  // Полско огнивче (scarlet pimpernel)
  LYSIMACHIA_ARVENSIS = 'Lysimachia arvensis',
  // Синя метличина (cornflower)
  CENTAUREA_CYANUS = 'Centaurea cyanus',
  // Див овес (wild oat)
  AVENA_FATUA = 'Avena fatua',
  // Овсига (Bromus)
  BROMUS = 'Bromus',
  // Фаларис (phalaris)
  PHALARIS_SPP = 'Phalaris spp.',
  // Пирей (quick grass)
  ELYMUS_REPENS = 'Elymus repens',
  // Троскот (bermuda grass)
  CYNODON_DACTYLON = 'Cynodon dactylon',
  // Лепка (catchweed)
  GALIUM_APARINE = 'Galium aparine',
  // Бутрак (beggartick)
  BIDENS_TRIPARTITA = 'Bidens tripartita',
  // Поветица. (field bindweed)
  CONVOLVULUS_ARVENSIS = 'Convolvulus arvensis',
  // Ветрушка (windgrass)
  APERA_SPICA_VENTI = 'Apera spica venti',
  // Кощрява (setaria)
  APERA_SPP = 'Apera spp.',
  // Абутилон (velvetleaf)
  ABUTILON_THEOPHRASTI = 'Abutilon theophrasti',
  // Паламида (plume thistles)
  CIRSIUM_ARVENSE = 'Cirsium arvense',
  // Подрумче (mayweed)
  ANTHEMIS_ARVENSIS = 'Anthemis arvensis',
  // Синап (white mustard)
  SINAPIS_ALBA = 'Sinapis alba',
  // Грахова листна въшка (pea aphid)
  ACYRTHOSIPHON_PISI = 'Acyrthosiphon pisi',
  // Детелинов хоботник (clover seed weevil)
  PROTAPION_APRICANS = 'Protapion apricans',
  // Малък люцернов листов хоботник (alfalfa weevil)
  HYPERA_POSTICA = 'Hypera postica',
  // Детелинов зърнояд (Seed beetle)
  BRUCHIDIUS_VARIUS = 'Bruchidius varius',
  // Грахова листна въшка (aphid midge)
  APHIDOLETES_APHIDIMYZA = 'Aphidoletes aphidimyza',
  // Нощенки (owlet moths)
  NOCTUIDAE = 'Noctuidae',
  // Скакалци (grasshoppers)
  CAELIFERA = 'Caelifera',
  // Педомерки. (geometer moths)
  GEOMETRIDAE = 'Geometridae',
  // Люцернов листояд (lucerne leaf beetle)
  GONIOCTENA_FORNICATA = 'Gonioctena fornicata',
  // Люцернов листов хоботник. (alfalfa weevil)
  PHYTONOMUS_VARIABILIS = 'Phytonomus variabilis',
  // Пъпкова галица (alfalfa leaf midge)
  DASYNEURA_IGNORATA = 'Dasyneura ignorata',
  // Цветова галица (alfalfa flower midge)
  CONTARINIA_MEDICAGINIS = 'Contarinia medicaginis',
  // Маков листояд. ()
  ENTOMOSCELIS_SULTATOR = 'Entomoscelis sultator',
  // Грахова листна въшка (puceron noir de la luzerne)
  APHIS_MEDICAGINIS = 'Aphis medicaginis',
  // Татул (jimsonweeds)
  DATURA_STRAMONIUM = 'Datura stramonium',
  // Телени червеи (lined click beetle)
  AGRIOTIS_LINEATUS = 'Agriotis lineatus',
  // Галообразуващ зелев хоботник (turnip gall weevil)
  CEUTORRHYNCHUS_PLEUROSTIGMA = 'Ceutorrhynchus pleurostigma',
  // Стоножки (centipedes)
  CHILOPODA = 'Chilopoda',
  // Зелеви мухи (cabbage root fly)
  CHORTOPHILA_BRASSICAE = 'Chortophila brassicae',
  // Майски бръмбар и Телени червеи. (cockchafer)
  MELOLONTHA_MELOLONTHA = 'Melolontha melolontha',
  // Грудков хоботник (root weevil)
  SITONA_SP = 'Sitona sp.',
  // Черна бобова листна въшка (bean aphid)
  APHIS_FABAE = 'Aphis fabae',
  // Тъмна грахова листозавивачка (bean aphid)
  LASPEYRESIA_NIGRICANA = 'Laspeyresia nigricana',
  // Грахов зърнояд (pea weevil)
  BRUCHUS_PISORUM = 'Bruchus pisorum',
  // Гамозначна нощенка (silver Y)
  AUTOGRAPHA_GAMMA = 'Autographa gamma',
  // Листни въшки (greenfly)
  APHIDOIDEA = 'Aphidoidea',
  // Хоботници. (true weevils)
  CURCULIONIDAE = 'Curculionidae',
  // Акари (mites)
  ACARINA = 'Acarina',
  // Оранжерийна белокрилка. (glasshouse whitefly)
  TRIALEURODES_VAPORARIORUM = 'Trialeurodes vaporariorum',
  // Аскохитоза (chickpea ascochyta blight fungus)
  ASCOCHYTA_RABIEI = 'Ascochyta rabiei',
  // Антракноза (brown leaf spot)
  ANTHRACNOSE = 'Anthracnose',
  // Брашнеста мана (powdery mildew)
  BLUMERIA_GRAMINIS = 'Blumeria graminis',
  // Бяло гниене (white mold)
  SCLEROTINIA_SCLEROTIORUM = 'Sclerotinia sclerotiorum',
  // Бяло гниене (Grey mould)
  BOTRYTIS_CINEREA = 'Botrytis cinerea',
  // Мана (Downy mildew)
  PERONOSPORACEAE = 'Peronosporaceae',
  // Ръжда. (black rust)
  PUCCINIA_GRAMINIS = 'Puccinia graminis',
  // Септориоза (Bacterial leaf spot)
  SEPTORIA = 'Septoria',
  // Бактериоза. ()
  XANTHOMONAS = 'Xanthomonas',
  // Северен листен пригор (northern corn leaf blight)
  SETOSPHAERIA_TURCICA = 'Setosphaeria turcica',
  // Полско лютиче (buttercups)
  RANUNCULUS_ARVENSIS = 'Ranunculus arvensis',
  // Трипси (Thrips)
  THYSANOPTERA = 'Thysanoptera',
  // Обикновена житна пиявица (cereal leaf beetle)
  OULEMA_MELANOPA = 'Oulema melanopa',
  // Овесена листна въшка (grain aphid)
  SITOBION_AVENAE = 'Sitobion avenae',
  // Цикади и др. (cicadas)
  CICADOIDEA = 'Cicadoidea',
  // Западен коренов царевичен червей. (corn rootworm)
  DIABROTICA_VIRGIFERA_ZEAE = 'Diabrotica virgifera zeae',
  // Царевичен стъблен пробивач (European corn worm)
  OSTRINIA_NUBILALIS = 'Ostrinia nubilalis',
  // Ливадна пеперуда. (beet webworm)
  LOXOSTEGE_STICTICALIS = 'Loxostege sticticalis',
  // Зърнов бръмбар (American wheat weevil)
  RHYZOPERTHA_DOMINICA = 'Rhyzopertha dominica',
  // Брашнен бръмбър (yellow mealworm beetle)
  TENEBRIO_MOLITOR = 'Tenebrio molitor',
  // Сив царевичен хоботник. (maize leaf weevil)
  TANYMECUS_DILATICOLLIS = 'Tanymecus dilaticollis',
  // Питиум (bacterial stalk rot of maize)
  PYTHIUM_APHANIDERMATUM = 'Pythium aphanidermatum',
  // Фузариум (fusarium head blight)
  FUSARIUM_GRAMINEARUM = 'Fusarium graminearum',
  // Ризоктония (Leaf and sheath blight)
  RHIZOCTONIA_ZEAE = 'Rhizoctonia zeae',

  //wiki
  WIKI = 'WIKI',
  WIKI_DESCRIPTION = 'WIKI_DESCRIPTION',
  WIKI_SOWING = 'WIKI_SOWING',
  WIKI_COMBINED = 'WIKI_COMBINED',
  WIKI_CHEMICAL_PROTECTION = 'WIKI_CHEMICAL_PROTECTION',

  WIKI_CHEMICAL_PROTECTION_START_HERE = 'WIKI_CHEMICAL_PROTECTION_START_HERE',
  WIKI_CHEMICAL_PROTECTION_PLANTS = 'WIKI_CHEMICAL_PROTECTION_PLANTS',
  WIKI_CHEMICAL_PROTECTION_ENEMIES = 'WIKI_CHEMICAL_PROTECTION_ENEMIES',
  WIKI_CHEMICAL_PROTECTION_CHEMICALS = 'WIKI_CHEMICAL_PROTECTION_CHEMICALS',
  WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENTS = 'WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENTS',

  WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_UNIT = 'WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_UNIT',
  WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_CHEMICALS_USING = 'WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_CHEMICALS_USING',
  WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_DOSAGE_INFO = 'WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_DOSAGE_INFO',
  WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_DOSAGE = 'WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_DOSAGE',
  WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_MAX_APPLICATIONS = 'WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_MAX_APPLICATIONS',
  WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_INTERVAL = 'WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_INTERVAL',
  WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_QUARANTINE = 'WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_QUARANTINE',
  WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PRICING = 'WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PRICING',
  WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PRICE_PER_LITER = 'WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PRICE_PER_LITER',
  WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PRICE_PER_ACRE = 'WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PRICE_PER_ACRE',
  WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_AFFECTED_PLANTS = 'WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_AFFECTED_PLANTS',
  WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_ADDITIONAL_INFO = 'WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_ADDITIONAL_INFO',

  WIKI_COMBINED_PLANT_TYPE = 'COMBINED_PLANT_TYPE',
  WIKI_COMBINED_MIN_SEEDING_RATE = 'COMBINED_MIN_SEEDING_RATE',
  WIKI_COMBINED_MAX_SEEDING_RATE = 'COMBINED_MAX_SEEDING_RATE',
  WIKI_COMBINED_PRICE_FOR_1KG_SEEDS = 'COMBINED_PRICE_FOR_1KG_SEEDS',
}

const LangMap: LangMapInterface = {
  BG: {
    //plants
    [SELECTABLE_STRINGS.PISUM_SATIVUM]: 'Грах',
    [SELECTABLE_STRINGS.GLYCINE_MAX]: 'Соя',
    [SELECTABLE_STRINGS.SORGHUM_VULGARE_VAR_TEHNICUM]: 'Сорго',
    [SELECTABLE_STRINGS.ZEA_MAYS]: 'Царевица',
    [SELECTABLE_STRINGS.MEDICAGO_SATIVA]: 'Люцерна',
    [SELECTABLE_STRINGS.TRIFOLIUM_STELLATUM]: 'Звездан',
    [SELECTABLE_STRINGS.TRIFOLIUM_PRATENSE]: 'Червена детелина',
    [SELECTABLE_STRINGS.TRIFOLIUM_REPENS]: 'Бяла детелина',
    [SELECTABLE_STRINGS.LOLIUM_PERENNE]: 'Пасищен райграс',
    [SELECTABLE_STRINGS.AGROPYRON_CRISTATUM]: 'Гребенчат житняк',
    [SELECTABLE_STRINGS.DACTYLIS_GLOMERATA]: 'Ежова главица',
    [SELECTABLE_STRINGS.AVENULA_PUBESCENS]: 'Безосилеста овсига',
    [SELECTABLE_STRINGS.FESTUCA_PRATENSIS]: 'Ливадна власатка',
    [SELECTABLE_STRINGS.FESTUCA_RUBRA]: 'Червена власатка',

    [SELECTABLE_STRINGS.THEME_LIGHT]: 'Светла тема',
    [SELECTABLE_STRINGS.THEME_DARK]: 'Тъмна тема',
    [SELECTABLE_STRINGS.THEME_SYSTEM]: 'Системна тема',

    [SELECTABLE_STRINGS.G_LITER]: 'g/l',
    [SELECTABLE_STRINGS.G_KG]: 'g/kg',
    [SELECTABLE_STRINGS.ML_ACRE]: 'ml/декър',
    [SELECTABLE_STRINGS.G_ACRE]: 'g/дедкър',
    [SELECTABLE_STRINGS.G_100_KG_SEEDS]: 'g/100 kg семена',

    [SELECTABLE_STRINGS.GET_STARTED]: 'Да започваме!',
    [SELECTABLE_STRINGS.HEADER_WELCOME]: 'Добре дошли, ',
    [SELECTABLE_STRINGS.MENU]: 'Меню',
    [SELECTABLE_STRINGS.HOME]: 'Начална страница',
    [SELECTABLE_STRINGS.REGISTER]: 'Регистрация',
    [SELECTABLE_STRINGS.LOGIN]: 'Вход',
    [SELECTABLE_STRINGS.LOGOUT]: 'Изход',
    [SELECTABLE_STRINGS.OR]: 'ИЛИ',
    [SELECTABLE_STRINGS.PROFILE]: 'Профил',
    [SELECTABLE_STRINGS.NEED_HELP_Q]: 'Нуждаете се от помощ?',
    [SELECTABLE_STRINGS.HAS_VALUE_OUTSIDE_SUGGESTED_RANGE]: 'Имате стойност извън препоръчаните!',
    [SELECTABLE_STRINGS.SAVE_CALCULATION]: 'Запази калкулацията',
    [SELECTABLE_STRINGS.CALCULATION_VISUALIZATION]: 'Визуализация на калкулацията',
    [SELECTABLE_STRINGS.LOADING]: 'Зареждане...',
    [SELECTABLE_STRINGS.HISTORY_HERE]: 'Ето вашата история на изчисления',
    [SELECTABLE_STRINGS.NO_HISTORY]: 'Нямате история? Сметнете нещо за да се появи тук!',
    [SELECTABLE_STRINGS.NO_HISTORY_SOWING_RATE]: 'Не е намерена история за сеитбена норма',
    [SELECTABLE_STRINGS.NO_HISTORY_SEEDING_DATA]: 'Не е намерена история за данни за сеитване',
    [SELECTABLE_STRINGS.SEARCH_PLACEHOLDER]: 'Търси...',
    [SELECTABLE_STRINGS.SELECT_DATE]: 'Избери дата',

    [SELECTABLE_STRINGS.HOME_PAGE_YOUR_TRUSTED_AGRO_CALCS]: 'Вашите верни земеделски калкулатори',
    [SELECTABLE_STRINGS.HOME_PAGE_PRECISION_FARMING]: 'Точна агрономия',
    [SELECTABLE_STRINGS.HOME_PAGE_PRECISION_FARMING_DESCRIPTION]:
      'Оптимизирайте вашите ресурси с прецизни изчисления, съобразени с вашите специфични култури и условия.',
    [SELECTABLE_STRINGS.HOME_PAGE_TIME_SAVING]: 'Спестява време',
    [SELECTABLE_STRINGS.HOME_PAGE_TIME_SAVING_DESCRIPTION]:
      'Спестете часове ръчни изчисления и планиране с нашия интуитивен, лесен за използване пакет калкулатор.',
    [SELECTABLE_STRINGS.HOME_PAGE_EXPERT_RECOMMENDATIONS]: 'Експертни препоръки',
    [SELECTABLE_STRINGS.HOME_PAGE_EXPERT_RECOMMENDATIONS_DESCRIPTION]:
      'Получавайте препоръки въз основа на най-добри земеделски практики и научни изследвания.',
    [SELECTABLE_STRINGS.HOME_PAGE_WHY_USE_AGRO_CALC]: 'Защо да използвате нашите калкулатори?',
    [SELECTABLE_STRINGS.HOME_PAGE_MODERN_FARMING_SOLUTIONS]: 'Съвременни агрономични решения',
    [SELECTABLE_STRINGS.HOME_PAGE_MODERN_FARMING_SOLUTIONS_DESCRIPTION]:
      'Прецизни инструменти за съвременния фермер, предназначени да увеличат максимално добива и ефективността.',
    [SELECTABLE_STRINGS.HOME_PAGE_OUR_SUITE_OF_CALCULATORS]:
      'Нашият пакет от селскостопански калкулатори помага на фермери, агрономи и селскостопански специалисти да правят решения, базирани на данни, за подобряване на добивите, намаляване на отпадъците и увеличаване на рентабилността.',

    [SELECTABLE_STRINGS.EMAIL]: 'Имейл',
    [SELECTABLE_STRINGS.PASSWORD]: 'Парола',
    [SELECTABLE_STRINGS.PASSWORD_CONFIRM]: 'Потвърди парола',
    [SELECTABLE_STRINGS.SUBMIT]: 'Изпрати',
    [SELECTABLE_STRINGS.NO_ACC_Q]: 'Нямате акаунт?',
    [SELECTABLE_STRINGS.HAVE_ACC_Q]: 'Имате акаунт?',

    [SELECTABLE_STRINGS.INVALID_EMAIL]: 'Невалиден имейл',
    [SELECTABLE_STRINGS.PASSWORD_MIN]: 'Паролата трябва да е поне 6 символа',
    [SELECTABLE_STRINGS.PASSWORD_HAS_LOWER]: 'Паролата трябва да съдържа поне една малка буква',
    [SELECTABLE_STRINGS.PASSWORD_HAS_UPPER]: 'Паролата трябва да съдържа поне една главна буква',
    [SELECTABLE_STRINGS.PASSWORD_HAS_NUMBER]: 'Паролата трябва да съдържа поне една цифра',
    [SELECTABLE_STRINGS.PASSWORD_HAS_SYMBOL]:
      'Паролата трябва да съдържа поне един специален символ',
    [SELECTABLE_STRINGS.PASSWORDS_DONT_MATCH]: 'Паролите не съвпадат',
    [SELECTABLE_STRINGS.FORGOT_PASSWORD]: 'Забрви паролата?',
    [SELECTABLE_STRINGS.REQUEST_PASSWORD_RESET]: 'Заявка за нулиране на парола',
    [SELECTABLE_STRINGS.RESET_PASSWORD]: 'Нулиране на парола',

    [SELECTABLE_STRINGS.TOAST_ERROR]: 'Възникна грешка',
    [SELECTABLE_STRINGS.TOAST_ERROR_SESSION_EXPIRED]: 'Вашата сесия е изтекла. Моля влезте отново.',
    [SELECTABLE_STRINGS.TOAST_ERROR_LOADING_DATA]: 'Възникна грешка при зареждането на данните',
    [SELECTABLE_STRINGS.TOAST_ERROR_NOT_LOGGED_IN]:
      'Трябва да сте влезли в профила си, за да запазите изчислението!',
    [SELECTABLE_STRINGS.TOAST_ERROR_NO_PLANT_SELECTED]: 'Не сте избрали растение за изчисление!',
    [SELECTABLE_STRINGS.TOAST_SAVE_SUCCESS]: 'Изчислението е запазено успешно!',
    [SELECTABLE_STRINGS.TOAST_REGISTER_SUCCESS]: 'Успешна регистрация! Моля влезте.',
    [SELECTABLE_STRINGS.TOAST_LOGIN_SUCCESS]: 'Успешен вход!',
    [SELECTABLE_STRINGS.TOAST_LOGOUT_SUCCESS]: 'Успешен изход!',
    [SELECTABLE_STRINGS.TOAST_TRY_AGAIN_LATER]: 'Моля опитайте по-късно',
    [SELECTABLE_STRINGS.TOAST_PASSWORD_RESET_REQUEST_PROCESSING]:
      'Изпращане на заявка за нулиране на парола...',
    [SELECTABLE_STRINGS.TOAST_PASSWORD_RESET_REQUEST_SENT]:
      'Заявка за нулиране на парола изпратена',
    [SELECTABLE_STRINGS.TOAST_ERROR_PASSWORD_RESET_REQUEST_FAILED]:
      'Възникна грешка при заявка за нулиране на парола',
    [SELECTABLE_STRINGS.TOAST_PASSWORD_RESET_SUCCESS]: 'Паролата е нулирана успешно!',
    [SELECTABLE_STRINGS.TOAST_ERROR_PASSWORD_RESET_FAILED]:
      'Възникна грешка при нулиране на паролата',

    [SELECTABLE_STRINGS.AGRICULTURAL_CALCULATORS]: 'Аграрни калкулатори',
    [SELECTABLE_STRINGS.SELECT_CALCULATOR]: 'Изберете калкулатор',
    [SELECTABLE_STRINGS.OPEN_CALCULATOR]: 'Отвори калкулатор',

    [SELECTABLE_STRINGS.SETTINGS]: 'Настройки',
    [SELECTABLE_STRINGS.SETTINGS_PREF_UNIT_OF_MEASUREMENT]: 'Предпочитана единица за измерване',
    [SELECTABLE_STRINGS.SETTINGS_THEME]: 'Тема',
    [SELECTABLE_STRINGS.SETTINGS_LANGUAGE]: 'Език',
    [SELECTABLE_STRINGS.SETTINGS_PREF_UNIT_OF_MEASUREMENT_ACRES]: 'Декари',
    [SELECTABLE_STRINGS.SETTINGS_PREF_UNIT_OF_MEASUREMENT_ACRES_SYMBOL]: 'дка',
    [SELECTABLE_STRINGS.SETTINGS_PREF_UNIT_OF_MEASUREMENT_HECTARES]: 'Хектари',
    [SELECTABLE_STRINGS.SETTINGS_PREF_UNIT_OF_MEASUREMENT_HECTARES_SYMBOL]: 'ha',

    [SELECTABLE_STRINGS.SOWING_RATE_CALC_TITLE]: 'Калкулатор за сеитбена норма',
    [SELECTABLE_STRINGS.SOWING_RATE_CALC_DESCRIPTION]:
      'Изчислете точната сеитбена норма за вашите култури',
    [SELECTABLE_STRINGS.SOWING_RATE_PICK_CULTURE]: 'Изберете култура',
    [SELECTABLE_STRINGS.SOWING_RATE_SELECTED_CULTURE]: 'Избрана култура',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_SUGGESTED_RANGE]: 'Препоръчителен диапазон',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_SUGGESTED_VALUE]: 'Препоръчителна стойност',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_COEFFICIENT_SECURITY]: 'Коефициент на сигурност',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_WANTED_PLANTS_PER_M2]: 'Желани растения на m²',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_MASS_PER_1000g_SEEDS]: 'Маса на 1000g семена',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_PURITY]: 'Чистота',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_GERMINATION]: 'Лабораторна кълняемост',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_ROW_SPACING]: 'Междуредно разстояние',
    [SELECTABLE_STRINGS.SOWING_RATE_INPUT_TOTAL_AREA]: 'Обща площ',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_SOWING_RATE]: 'Сеитбена норма',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_SOWING_RATE_SEEDS_PER_M2]: 'брой семена на m²',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_SOWING_RATE_PLANTS_PER_ACRE]: 'брой растения на дка',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_SOWING_RATE_PLANTS_PER_HECTARE]:
      'брой растения на хектар',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_USED_SEEDS]: 'Използвани семена',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_KA_PER_ACRE]: 'кг/дка',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_KA_PER_HECTARE]: 'кг/хектар',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_ROW_SPACING]: 'Междуредно разстояние',
    [SELECTABLE_STRINGS.SOWING_RATE_OUTPUT_ROW_SPACING_CM]: 'см',
    [SELECTABLE_STRINGS.SOWING_RATE_THIS_IS_SUGGESTED]:
      'Това е препоръчителната сеитбена норма базирана на въведените от вас параметри. Може да варира според конкретните условия на полето.',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ]: 'Визуализация на калкулацията',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_GENERAL]: 'Графично представяне на резултатите за',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_ALL_ELEMENTS]: 'Обща визуализация на параметрите',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_ELEMENTS_RELATIONSHIP]: 'Пропорции между параметрите',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_COMPARE_CALCED_PARAMS]:
      'Сравнение на изчислените стойности',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_COMPARE_CALCED_PARAMS_VECED]:
      'Стойностите са мащабирани за по-добра визуализация',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_PLANTING_EFFICIENCY]: 'Ефективност на сеитбата',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_PLANTING_EFFICIENCY_SEEDS_TO_PLANTS]: 'Семена→Растения',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_PLANTING_EFFICIENCY_COVERAGE]: 'Покритие',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_PLANTING_EFFICIENCY_DENSITY]: 'Гъстота',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_PLANTING_EFFICIENCY_EFFICIENCY]: 'Ефективност',
    [SELECTABLE_STRINGS.SOWING_RATE_VIZ_PLANTING_EFFICIENCY_SUGGESTED]:
      'Относителни показатели за качество на сеитбата',

    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_CULTURE_SELECT]: 'Избор на култура',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_CULTURE_SELECT_DESCRIPTION_SELECT_CULTURE_FIRST]:
      'Изберете културата, за която искате да направите изчисление на сеитбената норма първо',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_CULTURE_SELECT_DESCRIPTION]:
      'Изберете културата, за която искате да направите изчисление на сеитбената норма.',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_SAFETY_COEFFICIENT]: 'Коефициент на сигурност',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_SAFETY_COEFFICIENT_DESCRIPTION]:
      'Този коефициент (обикновено между 0.9 и 0.99) служи за осигуряване на буфер срещу неблагоприятни условия – загуби от неблагоприятно време, механични повреди и др. По-високата стойност означава, че ще бъдат заложени повече семена с цел компенсиране на евентуални загуби.',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_WANTED_PLANTS_PER_M2]: 'Желани брой растения на m²',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_WANTED_PLANTS_PER_M2_DESCRIPTION]:
      'Този параметър определя колко растения искаме да израснат на 1 кв. м. Обикновено стойността зависи от препоръките на агронома или сорта и е критичен за добива.',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_MASS_PER_1000g]: 'Маса на 1000g семена',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_MASS_PER_1000g_DESCRIPTION]:
      'Този параметър, изразен в грамове, се предоставя от семепроизводителя и влияе пряко върху изчисленията на използвалото количество семена',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_PURITY]: 'Чистота на семената',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_PURITY_DESCRIPTION]:
      'Изразява се като процент и показва доколко партидата съдържа само желаните семена, без примеси. Ако чистотата е по-ниска, системата автоматично ще увеличи нужната сеитбена норма.',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_GERMINATION]: 'Лабораторна кълняемост',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_GERMINATION_DESCRIPTION]:
      'Процент, показващ колко от семената ще поникнат при лабораторни условия. Това е критичен фактор за определяне на реалния брой растения на декар.',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_ROW_SPACING]: 'Междуредово разстояние',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_ROW_SPACING_DESCRIPTION]:
      'Тук потребителят задава разстоянието между редовете в сантиметри, според агротехническите изисквания. Това се използва при изчисляване на общата гъстота и равномерността на разпределение на семената.',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_VISUALIZATION]: 'Визуализация на резултатите',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_VISUALIZATION_DESCRIPTION]:
      'След въвеждане на всички параметри, калкулаторът показва графично основните резултати: брой растения на декар, разход на семена, междуредово разстояние, и други. Това позволява бърз анализ и вземане на агрономически решения.',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_TOTAL_AREA]: 'Обща площ',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_TOTAL_AREA_DESCRIPTION]:
      'Тук потребителят задава площта в декари, за която ще се извърши сеитбата. Този параметър е нужен за изчисляване на общото количество семена, което трябва да се осигури.',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_SAVE_CALCULATION]: 'Запазване на калкулацията',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_SAVE_CALCULATION_DESCRIPTION]:
      'След като всички параметри са въведени и резултатите са генерирани, потребителят може да запази конфигурацията. Това е полезно за бъдещи справки или за сравнение на различни сценарии.',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_ANALYSIS]: 'Анализ',
    [SELECTABLE_STRINGS.SOWING_RATE_TOUR_ANALYSIS_DESCRIPTION]:
      'Тук се вижда, или ще вижда, анализ с графики на вкараните данни.',

    [SELECTABLE_STRINGS.COMBINED_CALC_TITLE]: 'Сеитбена норма на смеска',
    [SELECTABLE_STRINGS.COMBINED_CALC_DESCRIPTION]:
      'Изчислете точната сеитбена норма за вашите смески от култури',
    [SELECTABLE_STRINGS.COMBINED_LEGUME_TITLE]: 'Многогодишни бобови фуражни култури',
    [SELECTABLE_STRINGS.COMBINED_CEREAL_TITLE]: 'Многогодишни житни фуражни култури',
    [SELECTABLE_STRINGS.COMBINED_SUMMARY_TITLE]: 'Обобщение на смеската',
    [SELECTABLE_STRINGS.COMBINED_TOTAL_PARTICIPATION]: 'Общо участие в смеската:',
    [SELECTABLE_STRINGS.COMBINED_FINAL_PRICE]: 'Крайна цена:',
    [SELECTABLE_STRINGS.COMBINED_VALUES_OUTSIDE_LIMIT]: 'Имате стойности извън препоръчани лимит!',
    [SELECTABLE_STRINGS.COMBINED_SAVE_CALCULATION]: 'Запази тази сметка',
    [SELECTABLE_STRINGS.COMBINED_VISUALIZATION_TITLE]: 'Визуализация на смеската',
    [SELECTABLE_STRINGS.COMBINED_VISUALIZATION_DESCRIPTION]:
      'Графично представяне на участието на културите в смеската',
    [SELECTABLE_STRINGS.COMBINED_TOTAL_PARTICIPATION_LABEL]: 'Общо участие',
    [SELECTABLE_STRINGS.COMBINED_MAX_PARTICIPATION]: 'Максимално',
    [SELECTABLE_STRINGS.COMBINED_ACTIVE]: 'Активно?',
    [SELECTABLE_STRINGS.COMBINED_PLANT]: 'Растиение',
    [SELECTABLE_STRINGS.COMBINED_PLEASE_SELECT_PLANT]: 'Моля, изберете',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE_SINGLE]: 'Сеидбена норма - самостоятелно',
    [SELECTABLE_STRINGS.COMBINED_PARTICIPATION_PERCENT]: 'Участие (%)',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE]: 'Сеитбена норма',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE_MIX]: 'Сеидбена норма - в смеската',
    [SELECTABLE_STRINGS.COMBINED_SEED_PRICE_PER_ACRE]: 'Цена на семена за дка/BGN',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE_BY_PLANT_TYPE]: 'Сеитбена норма по тип култура',
    [SELECTABLE_STRINGS.COMBINED_PARTICIPATION_DISTRIBUTION]: 'Разпределение на участията',
    [SELECTABLE_STRINGS.COMBINED_PRICE_PER_ACRE_COMPARISON]:
      'Сравнение на цената на семената за дка',
    [SELECTABLE_STRINGS.COMBINED_PRICE_PER_ACRE_COMPARISON_LABEL]: 'Цена на семена за дка/BGN',
    [SELECTABLE_STRINGS.COMBINED_PRICE_PER_HECTARE_COMPARISON]:
      'Сравнение на цената на семената за хектар',
    [SELECTABLE_STRINGS.COMBINED_PRICE_PER_HECTARE_COMPARISON_LABEL]:
      'Цена на семена за хектар/BGN',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE_COMPARISON]: 'Сравнение на сеитбените норми',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE_SINGLE_PLANT]: 'Сеитбена норма - самостоятелно',
    [SELECTABLE_STRINGS.COMBINED_SOWING_RATE_MIX_PLANT]: 'Сеитбена норма - в смеската',

    [SELECTABLE_STRINGS.COMBINED_TOUR_PERENNIAL_LEGUME]: 'Многогодишни бобови култури',
    [SELECTABLE_STRINGS.COMBINED_TOUR_PERENNIAL_LEGUME_DESCRIPTION]:
      'Този раздел обработва бобови култури като червена детелина, люцерна или други азотофиксиращи растения. Бобовите растения са ценни за подобряване на почвата и осигуряват богата на протеини фуражна маса.',
    [SELECTABLE_STRINGS.COMBINED_TOUR_CROP_ACTIVATION]: 'Активиране на култура',
    [SELECTABLE_STRINGS.COMBINED_TOUR_CROP_ACTIVATION_DESCRIPTION]:
      'Отметнете това поле, за да активирате определена култура във вашата смес. Само активираните култури ще бъдат включени в окончателното изчисление на нормата на засяване.',
    [SELECTABLE_STRINGS.COMBINED_TOUR_PLANT_SELECTION]: 'Избор на растение',
    [SELECTABLE_STRINGS.COMBINED_TOUR_PLANT_SELECTION_DESCRIPTION]:
      'Изберете конкретната сортова разновидност от падащото меню. Всяко растение има различни характеристики и изисквания за засяване.',
    [SELECTABLE_STRINGS.COMBINED_TOUR_SOWING_RATE_SINGLE]: 'Норма засяване в чист посев',
    [SELECTABLE_STRINGS.COMBINED_TOUR_SOWING_RATE_SINGLE_DESCRIPTION]:
      'Това показва препоръчителната норма на засяване, ако тази култура се засява самостоятелно, базирана на агрономически стандарти и характеристики на културата.',
    [SELECTABLE_STRINGS.COMBINED_TOUR_LEGUME_PARTICIPATION]: 'Процент участие на бобовите',
    [SELECTABLE_STRINGS.COMBINED_TOUR_LEGUME_PARTICIPATION_DESCRIPTION]:
      'Максилмалното участие на бобови в смеската. Максимума 60%',
    [SELECTABLE_STRINGS.COMBINED_TOUR_PARTICIPATION_PERCENT]: 'Процент участие',
    [SELECTABLE_STRINGS.COMBINED_TOUR_PARTICIPATION_PERCENT_DESCRIPTION]:
      'Действителният процент, който тази култура ще представлява в окончателната смес. Тази стойност се изчислява въз основа на настройките за участие и приоритетите на културите.',
    [SELECTABLE_STRINGS.COMBINED_TOUR_SOWING_RATE_MIXTURE]: 'Норма засяване в смес',
    [SELECTABLE_STRINGS.COMBINED_TOUR_SOWING_RATE_MIXTURE_DESCRIPTION]:
      'Коригираната норма на засяване за тази култура при използване в смес, изчислена чрез прилагане на процента участие към нормата за чист посев.',
    [SELECTABLE_STRINGS.COMBINED_TOUR_SEED_PRICE]: 'Цена на семената на декар',
    [SELECTABLE_STRINGS.COMBINED_TOUR_SEED_PRICE_DESCRIPTION]:
      'Въведете стойността на семената на площ за тази култура. Това помага за изчисляване на общата икономическа стойност на вашата посевна смес.',
    [SELECTABLE_STRINGS.COMBINED_TOUR_PERENNIAL_CEREAL]: 'Многогодишни житни култури',
    [SELECTABLE_STRINGS.COMBINED_TOUR_PERENNIAL_CEREAL_DESCRIPTION]:
      'Този раздел обработва житни и тревни култури като райграс, тимотейка или други злакови растения, които осигуряват структура и допълнителни растежни характеристики към бобовите.',
    [SELECTABLE_STRINGS.COMBINED_TOUR_CEREAL_PARTICIPATION]: 'Процент участие на житните',
    [SELECTABLE_STRINGS.COMBINED_TOUR_CEREAL_PARTICIPATION_DESCRIPTION]:
      'Максималния процент участие на житните/тревни култури във вашата смес. Максимума 40%!',
    [SELECTABLE_STRINGS.COMBINED_TOUR_MIXTURE_SUMMARY]: 'Обобщение на смесата',
    [SELECTABLE_STRINGS.COMBINED_TOUR_MIXTURE_SUMMARY_DESCRIPTION]:
      'Този панел предоставя изчерпателен преглед на вашата пълна смес, включително общи проценти на участие, крайни разходи и ключови показатели за комбинирания план за засяване.',
    [SELECTABLE_STRINGS.COMBINED_TOUR_TOTAL_PARTICIPATION]: 'Общо участие в смесата',
    [SELECTABLE_STRINGS.COMBINED_TOUR_TOTAL_PARTICIPATION_DESCRIPTION]:
      'Показва общия процент участие на всички активни култури.',
    [SELECTABLE_STRINGS.COMBINED_TOUR_FINAL_PRICE]: 'Крайна цена на смесата',
    [SELECTABLE_STRINGS.COMBINED_TOUR_FINAL_PRICE_DESCRIPTION]:
      'Общата стойност на декар за вашата пълна семенна смес, изчислена чрез комбиниране на стойностите на всички активни култури въз основа на техните проценти на участие и индивидуални цени.',
    [SELECTABLE_STRINGS.COMBINED_TOUR_SAVE_CALCULATION]: 'Запазване на изчислението',
    [SELECTABLE_STRINGS.COMBINED_TOUR_SAVE_CALCULATION_DESCRIPTION]:
      'Запазете пълната конфигурация на вашата смес за бъдеща справка, сравнение с други смеси или за генериране на подробни доклади и препоръки.',
    [SELECTABLE_STRINGS.COMBINED_TOUR_VISUALIZATION]: 'Визуализация на смесата',
    [SELECTABLE_STRINGS.COMBINED_TOUR_VISUALIZATION_DESCRIPTION]:
      'Визуални графики и диаграми, ако всичко е наред, които помагат за разбиране на състава, разходите и характеристиките на вашата семенна смес чрез различни аналитични перспективи.',

    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CALC_TITLE]: 'Растителна защита',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CALC_DESCRIPTION]:
      'Изберете химикал за защита на растенията',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_SELECT_CHEMICAL]: 'Изберете химикал',

    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEMICAL_TYPE_HERBICIDE]: 'Хербицид',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEMICAL_TYPE_INSECTICIDE]: 'Инсектицид',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEMICAL_TYPE_FUNGICIDE]: 'Фунгицид',

    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_APPLICATION_STAGE_PRE_EMERGENT]: 'Извън вегетационно',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_APPLICATION_STAGE_PRE_EMERGENT_AFTER_SOWING_BEFORE_EMERGENCE]:
      'Извън вегетационно (След сеитба, преди поникване)',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_APPLICATION_STAGE_PRE_EMERGENT_BEFORE_START_OF_GROWING_SEASON]:
      'Извън вегетационно (Преди започване на вегетацията)',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_APPLICATION_STAGE_PRE_EMERGENT_PRE_SOWING_SEEDS_TREATMENT]:
      'Извън вегетационно (Предсеитбено третиране на семената)',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_APPLICATION_STAGE_PRE_EMERGENT_DURING_SOWING]:
      'Извън вегетационно (По време на сеитбата)',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_APPLICATION_STAGE_POST_EMERGENT]: 'Вегетационно',

    //chemical protection chemicals
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_DUAL_GOLD_960_EC]: 'ДУАЛ ГОЛД 960 ЕК',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_DUAL_GOLD_960_EC_INFO]:
      'Внася се след сеитба, преди поникване на културата и на плевелите.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_DUAL_GOLD_960_EC_INFO_NOTES]:
      'За увеличаване ефикасността срещу широколистните плевели е препоръчително добавяне на противошироколистен хербицид в работния разтвор при третирането. Внасянето се извършва с работен разтвор от 30 до 60 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_EKLIPS_70_VDG]: 'ЕКЛИПС 70 ВДГ',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_EKLIPS_70_VDG_INFO]:
      'Внася се след сеитба, преди поникване на културата и на плевелите.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_EKLIPS_70_VDG_INFO_NOTES]:
      'За увеличаване ефикасността срещу широколистните плевели е препоръчително добавяне на противошироколистен хербицид в работния разтвор при третирането. Внасянето се извършва с работен разтвор от 30 до 60 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_LEOPARD_5_EC]: 'ЛЕОПАРД 5 ЕК',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_LEOPARD_5_EC_INFO]:
      'Внася се от първи до четвърти лист на люцерната и при височина на балура 10-20 cm.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_LEOPARD_5_EC_INFO_NOTES]:
      'Внасянето на хербицида да се извършва с работен разтвор от 30 до 40 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_LENTAGRAN_45_WP]: 'ЛЕНТАГРАН 45 ВП',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_LENTAGRAN_45_WP_INFO]:
      'Да се прилага в начални фенофази от развитието на плевелите, до трети троен лист на културата.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_LENTAGRAN_45_WP_INFO_NOTES]:
      'Не се препоръчва приложение на Лентагран ВП при активен летеж на медоносните пчели. Внасянето се извършва с работен разтвор от 20 до 60 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_PULSAR_40_SL]: 'ПУЛСАР 40',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_PULSAR_40_SL_INFO]:
      'Внася се във фаза втори-четвърти лист на културата с добавяне на 50 ml/acre прилепител ДЕШ.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_PULSAR_40_SL_INFO_NOTES]:
      'При млада люцерна (в годината на създаване на посева) се внася в доза 120 ml/acre един месец, след сеитба на културата. Внасянето се извършва с работен разтвор от 15 до 20 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_DECIS_100_EC]: 'ДЕЦИС 100 ЕК',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_DECIS_100_EC_INFO]:
      'Третирането да  се извършва при поява на неприятелите над икономическия праг на вредност.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_DECIS_100_EC_INFO_NOTES]:
      'Притежава много бърз инициален (нокдаун) ефект срещу голям брой неприятели. Внасянето да се извършва с работен разтвор от 40 до 140 l/acre вода в зависимост от наличното земеделско оборудване. Токсичен за медоносната пчела (SPe8)!',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_LAMDEX_EXTRA]: 'ЛАМДЕКС ЕКСТРА',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_LAMDEX_EXTRA_INFO]:
      'Да не се извършват повече от две третирания с инсектицида през вегетационния период на културата. Може да се прилага до 120 ml/acre.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_LAMDEX_EXTRA_INFO_NOTES]:
      'Ефикасен е срещу широк спектър от вредители. Внасянето да се извършва с работен разтвор от 50 до 100 l/acre вода в зависимост от наличното земеделско оборудване. Токсичен е за медоносната пчела (SPe8)!',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_METEOR]: 'МЕТЕОР',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_METEOR_INFO]:
      'Третирането да  се извършва при поява на неприятелите над икономическия праг на вредност.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_METEOR_INFO_NOTES]:
      'Широкоспектърен несистемен пиретроиден инсектицид със стомашно и контактно действие. Третирането да се извършва с работен разтвор от 60 до 80 l/acre вода в зависимост от наличната земеделска техника.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_SUMI_ALPHA_5_EC]: 'СУМИ АЛФА 5 ЕК',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_SUMI_ALPHA_5_EC_INFO]:
      'Третирането да  се извършва при поява на неприятелите над икономическия праг на вредност.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_SUMI_ALPHA_5_EC_INFO_NOTES]:
      'Несистемен широкоспектърен пиретроиден инсектицид от пето поколение с контактно (парализиращо) и стомашно действие с много бърз инициален (нокдаун) ефект. Инсектицида е със силен репелент ефект - отблъсква медоносните пчели от третираната площ. Внасянето да се извършва с работен разтвор от 20 до 50 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_MOSPILAN_20_SG]: 'МОСПИЛАН 20 СГ',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_MOSPILAN_20_SG_INFO]:
      'Третирането да  се извършва при поява на неприятелите над икономическия праг на вредност.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_MOSPILAN_20_SG_INFO_NOTES]:
      'Ефикасен системен неоникотиноид инсектицид с контактно и стомашно действие. Може да се прилага в доза до 10 g/acre. Внасянето се извършва с работен разтвор от 50 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_STOMP_AQUA]: 'СТОМП АКВА',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_STOMP_AQUA_INFO]:
      'Внася се след сеитба, преди поникване на културата и на плевелите.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_STOMP_AQUA_INFO_NOTES]:
      'Може да се използва в доза до 300 ml/acre. Да не се третира при температури над 30 °С поради силно изпарение на работния разтвор. Внасянето се извършва с работен разтвор от 20 до 60 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_CHALLENGE_600_SC]: 'ЧЕЛЕНДЖ 600 СК',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_CHALLENGE_600_SC_INFO]:
      'Внася се след сеитба, преди поникване на културата и на плевелите.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_CHALLENGE_600_SC_INFO_NOTES]:
      'Внасянето се извършва с работен разтвор от 10 до 30 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_STRATOS_ULTRA]: 'СТРАТОС УЛТРА',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_STRATOS_ULTRA_INFO]:
      'Внасянето на хербицида да не си извършва при резки температурни амплитуди (голяма разлика между дневна и нощна температура), както и при наводнени или силно засушени посеви.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_STRATOS_ULTRA_INFO_NOTES]:
      'Най-добро усвояване на хербицида се получава при Температурния диапазон от 8.0 до 25,0° С подобрява усвояването на хербицида от чувствителните плевели и повишава хербицидната ефикасност. Превалявания от дъжд 1 час след третиране, не намалява ефикасността на продукта. Внасянето се извършва с работен разтвор от 15 до 20 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_ACHIBA_MAX]: 'АЧИБА МАКС',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_ACHIBA_MAX_INFO]:
      'Внасянето на хербицида може да се извърши във фаза първи същински лист и/или в пълна зрялост на граха (при производство на семена).',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_ACHIBA_MAX_INFO_NOTES]:
      'Внасянето се извършва с работен разтвор от 20 до 40 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_CORUM]: 'КОРУМ',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_CORUM_INFO]:
      'Внася се във втори същински лист на граха, с добавяне на адювант (прилепител) ДЕШ ХЦ в концентрация 0,25 – 0,3% в работния разтвор.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_CORUM_INFO_NOTES]:
      'Внасянето се извършва с работен разтвор от 20 до 30 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_LEBRON_0_5_G]: 'ЛЕБРОН 0,5 Г',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_LEBRON_0_5_G_INFO]:
      'Внася се едновременно със сеитбата на културата на дълбочина в почвата 4-5 cm.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_LEBRON_0_5_G_INFO_NOTES]:
      'Инсектицид за почвено приложение срещу почвени неприятели от групата на пиретроидите, действа контактно и чрез газовата си фаза в почвата, разпространява се в орницата. Инсектицидът може да се прилага в доза до 2,0 kg продукт / da.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_OASIS_5_EC]: 'ОАСИС 5 ЕК',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_OASIS_5_EC_INFO]:
      'Внасянето се извършва при поява на неприятелите над икономическия праг на вредност.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_OASIS_5_EC_INFO_NOTES]:
      'Притежава много бърз инициален (нокдаун) ефект срещу широка спектър от вредители. Внасянето се извършва с работен разтвор от 20 до 50 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_CITRINE_MAX]: 'ЦИТРИНЕ МАКС',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_CITRINE_MAX_INFO]:
      'Внасянето се извършва при поява на неприятелите над икономическия праг на вредност.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_CITRINE_MAX_INFO_NOTES]:
      'Притежава много бърз инициален (нокдаун) ефект срещу широк спектър от вредители. Внасянето се извършва с работен разтвор от 10 до 100 l/acre вода в зависимост от наличното земеделско оборудване. Токсичен е за медоносната пчела (SPe8)!',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_FLIPPER]: 'ФЛИПЕР ЕВ',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_FLIPPER_INFO]:
      'Третирането на посева се извършва при поява на неприятелите над икономическия праг на вредност. Може да се прилага в доза до 2000 ml/acre.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_FLIPPER_INFO_NOTES]:
      'Биологичен, контактен инсектицид / акарицид за борба срещу широк спектър от неприятели. Разрешен е за употреба при полски и оранжерийни условия. Внасянето се извършва с работен разтвор от 30 до 200 l/acre вода в зависимост от наличното земеделско оборудване. Безвреден за медоносната пчела!',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_ORTIVA_TOP_SC]: 'ОРТИВА ТОП СК',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_ORTIVA_TOP_SC_INFO]:
      'Третирането на посева с фунгицида се извършва превантивно или при поява на първи симптоми на заболяването.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_ORTIVA_TOP_SC_INFO_NOTES]:
      'Комбиниран широкоспектърен фунгицид с контактно и системно действие. Внасянето се извършва с работен разтвор от 50 до 100 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_SWITCH_625_WG]: 'СУИЧ 62.5 ВГ',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_SWITCH_625_WG_INFO]:
      'Внасянето се извършва при поява на заболяванията над икономическия праг на вредност.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_SWITCH_625_WG_INFO_NOTES]:
      'Комбиниран широкоспектърен фунгицид с несистемно предпазно, и системно предпазно и лечебно действие. Може да се прилага в доза до 100 g/acre.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_BORDEAUX_MIX_20_VP]: 'БОРДО МИКС 20 ВП',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_BORDEAUX_MIX_20_VP_INFO]:
      'Внасянето се извършва при поява на заболяванията над икономическия праг на вредност.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_BORDEAUX_MIX_20_VP_INFO_NOTES]:
      'Широкоспектърен контактен неорганичен фунгицид / бактерицид с предпазно действие, при максимална доза на приложение 500 g/acre. Внасянето се извършва с работен разтвор от  100 l/acre вода в зависимост от наличното земеделско оборудване. Подходящ е за употреба в биологичното земеделие при биологично производство.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_SULPHUR_WG]: 'СЯРА ВГ',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_SULPHUR_WG_INFO]:
      'Третирането се извършва при благоприятни метеорологични условия за развитие на болестта.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_SULPHUR_WG_INFO_NOTES]:
      'Несистемен неорганичен фунгицид и акарицид с контактно и фумигиращо действие. Внасянето се извършва с работен разтвор от 50 до 100 l/acre вода в зависимост от наличното земеделско оборудване. Подходящ за употреба в биологичното земеделие.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_ZOXIS_250_SC]: 'ЗОКСИС 250 СК',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_ZOXIS_250_SC_INFO]:
      'Третирането се извършва при благоприятни метеорологични условия за развитие на заболяванията.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_ZOXIS_250_SC_INFO_NOTES]:
      'Системен фунгицид с предпазно и лечебно действие. Позволява да се прилага в максимална доза до 100 ml/acre. Внасянето се извършва с работен разтвор 80 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_SIRTAKI]: 'СИРТАКИ',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_SIRTAKI_INFO]:
      'Третирането се извършва след сеитба, преди поникване на културата и на плевелите. Хербицидът може да се прилага  до четвърти троен лист на соята в доза 30 ml/acre.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_SIRTAKI_INFO_NOTES]:
      'За по-висока ефикасност на хербицида, плевелните видове трябва да са в начални фази от развитието си. Внасянето се извършва с работен разтвор от 20 до 50 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_SALTUS]: 'САЛТУС',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_SALTUS_INFO]:
      'Внася се във втори – четвърти троен лист на соята.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_SALTUS_INFO_NOTES]:
      'Селективен системен хербицид. Внасянето се извършва с работен разтвор от 10 до 40 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_PANTHER_40_EC]: 'ПАНТЕР 40 ЕК',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_PANTHER_40_EC_INFO]:
      'Внася се във втори – четвърти троен лист, преди начало на цъфтеж на соята.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_PANTHER_40_EC_INFO_NOTES]:
      'Не изисква добавяне на прилепител или омокрител към работния разтвор. Внасянето се извършва с работен разтвор от 20 до 40 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_DECA_EC]: 'ДЕКА ЕК',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_DECA_EC_INFO]:
      'Внасянето се извършва при поява на неприятелите над икономическия праг на вредност.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_DECA_EC_INFO_NOTES]:
      'Притежава бърз инициален (нокдаун) ефект срещу широк спектър от неприятели. Внасянето се извършва с работен разтвор до 100 l/acre вода в зависимост от наличното земеделско оборудване. Токсичен е за медоносната пчела (SPe8)!',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_TRIKA_EXPERT]: 'ТРИКА ЕКСПЕРТ',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_TRIKA_EXPERT_INFO]:
      'Прилага се локализирано, по време на сеитба в браздата.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_TRIKA_EXPERT_INFO_NOTES]:
      'Поставянето на инсектицида до семената по време на сеитба или до корените по време на окопаване/загърляне формира образуването на защитен филм около семето или коренчетата, предпазва от почвени инсекти като гъсеници на нощенки, ларви на бръмбари, телени червеи и други неприятели. В гранулите на Трика Експерт, като коформуланти са включени азот и фосфор в съотношение 7:35. Поради тази причина с прилагането на препарата се постига двоен ефект- предпазване и подхранване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_RETENGO_20_EC]: 'РЕТЕНГО 20 ЕК',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_RETENGO_20_EC_INFO]:
      'Третирането на посева може да се извърши от поникване до пълно оформяне на бобовите на соята.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_RETENGO_20_EC_INFO_NOTES]:
      'Системен неорганичен фунгицид и акарицид с контактно и фумигиращо действие. Подходящ за употреба в биологичното земеделие. Внасянето на фунгицида се извършва с работен разтвор от 10 до 40 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_DIFKOR_250_SC]: 'ДИФКОР 250 СК',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_DIFKOR_250_SC_INFO]:
      'Третирането на посева може да се извършва от поникване до пълна зрялост на соята при поява на неприятелите над икономическия праг на вредност. Може да се прилага в доза до 2000 ml/da.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_DIFKOR_250_SC_INFO_NOTES]:
      'Биологичен, контактен инсектицид / акарицид за борба срещу различни неприятели в стадии - яйца, ларви и възрастни насекоми. Разрешен е за употреба при полски и оранжерийни условия. Внасянето се извършва с работен разтвор от 30 до 200 l/da вода в зависимост от наличното земеделско оборудване. Безвреден за пчелите!',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_AGROXONE_500_SL]: 'АГРАКСОН 500 СЛ',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_AGROXONE_500_SL_INFO]:
      'Третирането може да се извършва до четвърти лист на културата.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_AGROXONE_500_SL_INFO_NOTES]:
      'Селективен, системен, хормоноподобен хербицид, предназначен за борба с едногодишните и многогодишни, широколистни плевели. Внасянето се извършва с работен разтвор от 40 до 60 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_GENERO_480_SL]: 'ДЖАНЕРО 480 СЛ',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_GENERO_480_SL_INFO]:
      'Третирането се извършва ранно вегетационно от втори лист до шести лист на културата.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_GENERO_480_SL_INFO_NOTES]:
      'Внасянето се извършва с работен разтвор от 10 до 40 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_KIDEKA_PRO]: 'КИДЕКА ПРО',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_KIDEKA_PRO_INFO]:
      'Третирането на соргото може да се извърши от втори до девети лист на културата.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_KIDEKA_PRO_INFO_NOTES]:
      'Системен хербицид с почвено действие. Инхибира нарастването на чувствителните плевелни видове до два дни след приложението му. Внасянето се извършва с работен разтвор от 8 до 40 l/acre вода при интервал между приложенията 10 дни в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_COLOMBO_PRO]: 'КОЛОМБО ПРО',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_COLOMBO_PRO_INFO]:
      'Прилага се на дълбочина до 4 cm в почвата.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_COLOMBO_PRO_INFO_NOTES]:
      'Нecиcтeмeн пиpeтpoидeн инceĸтицид c ĸoнтaĸтнo и cтoмaшнo дeйcтвиe.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_SIVANTO_ENERGY]: 'СИВАНТО ЕНЕРДЖИ',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_SIVANTO_ENERGY_INFO]:
      'Третирането се извършва при благоприятни метеорологични условия за поява на вредителите.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_SIVANTO_ENERGY_INFO_NOTES]:
      'Системен, вегетационен двукомпонентен инсектицид с комбинирано (системно и контактно) действие срещу широка гама от вредители. Внасянето се извършва с работен разтвор от 40 до 80 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_BISMARCK_KS]: 'БИСМАРК КС',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_BISMARCK_KS_INFO]:
      'Внася се след сеитба, преди поникване на културата и на плевелите.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_BISMARCK_KS_INFO_NOTES]:
      'Чувствителните плевелни видове могат да бъдат контролирани в ранните етапи от развитието им. Внасянето се извършва с работен разтвор от 40 до 140 l/acre вода в зависимост от наличното земеделско оборудване. Хербицидът може да се прилага  в доза до 200 ml/acre при царевицата.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_ARRAT]: 'АРАТ',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_ARRAT_INFO]:
      'Третирането на царевицата се извършва от втори лист до шести лист на културата.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_ARRAT_INFO_NOTES]:
      'Използването на хербицида не се препоръчва при преовлажнени или при засушени посеви. Третирането се извършва с работен разтвор от 20 до 40 l/acre вода в зависимост от наличното земеделско оборудване. Да не се използва при сладка царевица!',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_AMINOPIELIK_600_SL]: 'АМИНОПИЕЛИК 600 СЛ',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_AMINOPIELIK_600_SL_INFO]:
      'Внася се от трети до пети лист на културата.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_AMINOPIELIK_600_SL_INFO_NOTES]:
      'Хербицидът е с бърз инициален ефектът срещу чувствителните плевелни видове. Първите фитосимптоматични повреди се визуализират на следващия ден ден след третирането. Третирането се извършва с работен разтвор от 30 до 40 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_JANERO_480_SL]: 'ДЖАНЕРО 480 СЛ',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_JANERO_480_SL_INFO]:
      'Внася се от втори до шести лист на културата.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_JANERO_480_SL_INFO_NOTES]:
      'Да не се използва на варовити почви, поради вероятност да предизвика фитотоксичност при царевицата.Третирането на посевите се извършва с работен разтвор от 27,5 до 30 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_CORAGEN_20_SC]: 'КОРАГЕН 20 СК',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_CORAGEN_20_SC_INFO]:
      'Третирането на посева се извършва при поява на неприятелите над икономическия праг на вредност.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_CORAGEN_20_SC_INFO_NOTES]:
      'Инсектицидът е със стомашно, контактно действие и последействие, като запазва високата си активност до14-21 дни след третиране. Внасянето  се извършва с работен разтвор от 30 до 80 l/acre вода в зависимост от наличното земеделско оборудване.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_K_OBIOL_6_ULV]: 'К-ОБИОЛ 6 УЛВ',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_K_OBIOL_6_ULV_INFO]:
      'Борба със складови неприятели - Житояди (Гъгрици), Брашнени бръмбъри, Зърнопробивачи, Грахови и Бобови гъгрици, Молци.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_K_OBIOL_6_ULV_INFO_NOTES]:
      'Инсектицидът успешно контролира вредителите във всички   фази от развитието им  – яйце, ларва, пупа и възрастно насекомо (имаго).  Напълно безопасен и съгласуван с всички Европейски и световни наредби.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_INAZUMA]: 'ИНАЗУМА',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_INAZUMA_INFO]:
      'Третирането на посева се извършва двукратно през 14 дни при поява на неприятеля над икономическия праг на вредност, до изметляване на царевицата.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_INAZUMA_INFO_NOTES]:
      'Внасянето на инсектицида се извършва с работен разтвор от 30 до 50 l/acre вода в зависимост от наличното земеделско оборудване. Да не се прилага при култури в периода на активен цъфтеж или при наличие на цъфтяща плевелна растителност. Токсичен е за медоносната пчела (SPe8)!',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_REDIGO_M]: 'РЕДИГО М',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_REDIGO_M_INFO]:
      'Използва се да предсеитбено обеззаразяване на семената.',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_CHEM_REDIGO_M_INFO_NOTES]:
      'Обеззаразяването на семената от царевицата сеизвършва с работен разтвор от 0,1 до 1,9 l вода за 100 kg семена. Препоръчителна доза за приложение на фунгицида е 15 ml продукт на 50 000 бр. семена, при сеитбена норма 10 000 семена на da. Да се използват специализирани машини за обеззаразяване на семена.',

    //chemical active ingredients
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENTS]: 'Активни вещества',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_S_METOLACHLOR]: 'S-метолахлор',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_METRIBUZIN]: 'метрибузин',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_QUIZALOFOP_P_ETHYL]:
      'квизалофоп-П-етил',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PYRIDATE]: 'пиридат',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_IMAZAMOX]: 'имазамокс',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_DELTAMETHRIN]: 'делтаметрин',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_LAMBDA_CYHALOTHRIN]:
      'ламбда-цихалотрин',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_ESFENVALERATE]: 'eсфенвалерат',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_ACETAMIPRID]: 'ацетамиприд',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PENDIMETHALIN]: 'пендиметалин',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_ACLONIFEN]: 'аклонифен',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_CYCLOXYDIM]: 'циклоксидим',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_BENTAZONE]: 'бентазон',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_TEFLUTHRIN]: 'тефлутрин',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_FATTY_ACIDS]: 'мастни киселини',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_AZOXYSTROBIN]: 'азоксистробин',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_DIFENOCONAZOLE]: 'дифеноконазол',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_FLUDIOXONIL]: 'флудиоксонил',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_CYPRODINIL]: 'ципродинил',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_BORDEAUX_MIXTURE]:
      'бордолезова смес (меднокалциев сулфат)',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_SULFUR]: 'сяра',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_CLOMAZONE]: 'кломазон',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_QUIZALOFOP_P_TEFRIL]:
      'квизалофоп-П-тефурил',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PYRACLOSTROBIN]: 'пиракостробин',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_MCPA]: 'МЦПА',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_DICAMBA]: 'дикамба',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_MESOTRIONE]: 'мезотрион',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_CYPERMETHRIN]: 'циперметрин',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_FLUPYRADIFURON]: 'флупирадифурон',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_TRITOSULFURON]: 'тритосулфурон',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_2_4D_AMINE_SALT]: '2,4-Д аминна сол',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_RYNAXYPYR]: 'ринаксипир',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PROTHIOCONAZOLE]: 'протиоконазол',
    [SELECTABLE_STRINGS.CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_METALAXYL]: 'металаксил',

    //chemical protection enemies
    [SELECTABLE_STRINGS.SORGHUM_HALEPENSE]: 'Балур',
    [SELECTABLE_STRINGS.CYPERUS_STRIGOSUS]: 'Кисела трева',
    [SELECTABLE_STRINGS.ECHINOCHLOA_CRUS_GALLI]: 'Кокоше просо',
    [SELECTABLE_STRINGS.DIGITARIA_SANGUINALIS]: 'Кръвно просо',
    [SELECTABLE_STRINGS.SETARIA_SPP]: 'Кощрява',
    [SELECTABLE_STRINGS.APERA_SPР]: 'Метлица',
    [SELECTABLE_STRINGS.CAPSELLA_BURSA_PASTORIS]: 'Овчарска торбичка',
    [SELECTABLE_STRINGS.PORTULACA_OLERACEA]: 'Тученица',
    [SELECTABLE_STRINGS.SOLANUM_NIGRUM]: 'Черно куче грозде',
    [SELECTABLE_STRINGS.AMARANTHUS]: 'Щир',
    [SELECTABLE_STRINGS.ALOPECURUS_MYOSUROIDES]: 'Лисича опашка',
    [SELECTABLE_STRINGS.LOLIUM]: 'Райграс',
    [SELECTABLE_STRINGS.AMARANTHUS_RETROFLEXUS]: 'Червена мъртва коприва',
    [SELECTABLE_STRINGS.CHENOPODIUM_ALBUM]: 'Лобода',
    [SELECTABLE_STRINGS.PERSICARIA_HYDROPIPER]: 'Водно пипериче',
    [SELECTABLE_STRINGS.VERONICA_OFFICINALIS]: 'Великденче',
    [SELECTABLE_STRINGS.STELLARIA_MEDIA]: 'Врабчови чревца',
    [SELECTABLE_STRINGS.MATRICARIA_RECUTITA]: 'Лайка',
    [SELECTABLE_STRINGS.RAPHANUS_RAPHANISTRUM]: 'Дива ряпа',
    [SELECTABLE_STRINGS.GERANIUM_SP]: 'Типове здравец',
    [SELECTABLE_STRINGS.SENECIO_VULGARIS]: 'Спореж',
    [SELECTABLE_STRINGS.LAMIUM_PURPUREUM]: 'Червена мъртва коприва',
    [SELECTABLE_STRINGS.SINAPIS_ARVENSIS]: 'Синап',
    [SELECTABLE_STRINGS.LYSIMACHIA_ARVENSIS]: 'Полско огнивче',
    [SELECTABLE_STRINGS.CENTAUREA_CYANUS]: 'Синя метличина',
    [SELECTABLE_STRINGS.AVENA_FATUA]: 'Див овес',
    [SELECTABLE_STRINGS.BROMUS]: 'Овсига',
    [SELECTABLE_STRINGS.PHALARIS_SPP]: 'Фаларис',
    [SELECTABLE_STRINGS.ELYMUS_REPENS]: 'Пирей',
    [SELECTABLE_STRINGS.CYNODON_DACTYLON]: 'Троскот',
    [SELECTABLE_STRINGS.GALIUM_APARINE]: 'Лепка',
    [SELECTABLE_STRINGS.BIDENS_TRIPARTITA]: 'Бутрак',
    [SELECTABLE_STRINGS.CONVOLVULUS_ARVENSIS]: 'Поветица.',
    [SELECTABLE_STRINGS.APERA_SPICA_VENTI]: 'Ветрушка',
    [SELECTABLE_STRINGS.APERA_SPP]: 'Кощрява',
    [SELECTABLE_STRINGS.ABUTILON_THEOPHRASTI]: 'Абутилон',
    [SELECTABLE_STRINGS.CIRSIUM_ARVENSE]: 'Паламида',
    [SELECTABLE_STRINGS.ANTHEMIS_ARVENSIS]: 'Подрумче',
    [SELECTABLE_STRINGS.SINAPIS_ALBA]: 'Синап',
    [SELECTABLE_STRINGS.ACYRTHOSIPHON_PISI]: 'Грахова листна въшка',
    [SELECTABLE_STRINGS.PROTAPION_APRICANS]: 'Детелинов хоботник',
    [SELECTABLE_STRINGS.HYPERA_POSTICA]: 'Малък люцернов листов хоботник',
    [SELECTABLE_STRINGS.BRUCHIDIUS_VARIUS]: 'Детелинов зърнояд',
    [SELECTABLE_STRINGS.APHIDOLETES_APHIDIMYZA]: 'Грахова листна въшка',
    [SELECTABLE_STRINGS.NOCTUIDAE]: 'Нощенки',
    [SELECTABLE_STRINGS.CAELIFERA]: 'Скакалци',
    [SELECTABLE_STRINGS.GEOMETRIDAE]: 'Педомерки.',
    [SELECTABLE_STRINGS.GONIOCTENA_FORNICATA]: 'Люцернов листояд',
    [SELECTABLE_STRINGS.PHYTONOMUS_VARIABILIS]: 'Люцернов листов хоботник.',
    [SELECTABLE_STRINGS.DASYNEURA_IGNORATA]: 'Пъпкова галица',
    [SELECTABLE_STRINGS.CONTARINIA_MEDICAGINIS]: 'Цветова галица',
    [SELECTABLE_STRINGS.ENTOMOSCELIS_SULTATOR]: 'Маков листояд.',
    [SELECTABLE_STRINGS.APHIS_MEDICAGINIS]: 'Грахова листна въшка',
    [SELECTABLE_STRINGS.DATURA_STRAMONIUM]: 'Татул',
    [SELECTABLE_STRINGS.AGRIOTIS_LINEATUS]: 'Телени червеи',
    [SELECTABLE_STRINGS.CEUTORRHYNCHUS_PLEUROSTIGMA]: 'Галообразуващ зелев хоботник',
    [SELECTABLE_STRINGS.CHILOPODA]: 'Стоножки',
    [SELECTABLE_STRINGS.CHORTOPHILA_BRASSICAE]: 'Зелеви мухи',
    [SELECTABLE_STRINGS.MELOLONTHA_MELOLONTHA]: 'Майски бръмбар и Телени червеи.',
    [SELECTABLE_STRINGS.SITONA_SP]: 'Грудков хоботник',
    [SELECTABLE_STRINGS.APHIS_FABAE]: 'Черна бобова листна въшка',
    [SELECTABLE_STRINGS.LASPEYRESIA_NIGRICANA]: 'Тъмна грахова листозавивачка',
    [SELECTABLE_STRINGS.BRUCHUS_PISORUM]: 'Грахов зърнояд',
    [SELECTABLE_STRINGS.AUTOGRAPHA_GAMMA]: 'Гамозначна нощенка',
    [SELECTABLE_STRINGS.APHIDOIDEA]: 'Листни въшки',
    [SELECTABLE_STRINGS.CURCULIONIDAE]: 'Хоботници.',
    [SELECTABLE_STRINGS.ACARINA]: 'Акари',
    [SELECTABLE_STRINGS.TRIALEURODES_VAPORARIORUM]: 'Оранжерийна белокрилка.',
    [SELECTABLE_STRINGS.ASCOCHYTA_RABIEI]: 'Аскохитоза',
    [SELECTABLE_STRINGS.ANTHRACNOSE]: 'Антракноза',
    [SELECTABLE_STRINGS.BLUMERIA_GRAMINIS]: 'Брашнеста мана',
    [SELECTABLE_STRINGS.SCLEROTINIA_SCLEROTIORUM]: 'Бяло гниене',
    [SELECTABLE_STRINGS.BOTRYTIS_CINEREA]: 'Бяло гниене',
    [SELECTABLE_STRINGS.PERONOSPORACEAE]: 'Мана',
    [SELECTABLE_STRINGS.PUCCINIA_GRAMINIS]: 'Ръжда.',
    [SELECTABLE_STRINGS.SEPTORIA]: 'Септориоза',
    [SELECTABLE_STRINGS.XANTHOMONAS]: 'Бактериоза.',
    [SELECTABLE_STRINGS.SETOSPHAERIA_TURCICA]: 'Северен листен пригор',
    [SELECTABLE_STRINGS.RANUNCULUS_ARVENSIS]: 'Полско лютиче',
    [SELECTABLE_STRINGS.THYSANOPTERA]: 'Трипси',
    [SELECTABLE_STRINGS.OULEMA_MELANOPA]: 'Обикновена житна пиявица',
    [SELECTABLE_STRINGS.SITOBION_AVENAE]: 'Овесена листна въшка',
    [SELECTABLE_STRINGS.CICADOIDEA]: 'Цикади и др.',
    [SELECTABLE_STRINGS.DIABROTICA_VIRGIFERA_ZEAE]: 'Западен коренов царевичен червей.',
    [SELECTABLE_STRINGS.OSTRINIA_NUBILALIS]: 'Царевичен стъблен пробивач',
    [SELECTABLE_STRINGS.LOXOSTEGE_STICTICALIS]: 'Ливадна пеперуда.',
    [SELECTABLE_STRINGS.RHYZOPERTHA_DOMINICA]: 'Зърнов бръмбар',
    [SELECTABLE_STRINGS.TENEBRIO_MOLITOR]: 'Брашнен бръмбър',
    [SELECTABLE_STRINGS.TANYMECUS_DILATICOLLIS]: 'Сив царевичен хоботник.',
    [SELECTABLE_STRINGS.PYTHIUM_APHANIDERMATUM]: 'Питиум',
    [SELECTABLE_STRINGS.FUSARIUM_GRAMINEARUM]: 'Фузариум',
    [SELECTABLE_STRINGS.RHIZOCTONIA_ZEAE]: 'Ризоктония',

    //wiki
    [SELECTABLE_STRINGS.WIKI]: 'Wiki',
    [SELECTABLE_STRINGS.WIKI_DESCRIPTION]:
      'Welcome to our comprehensive agricultural knowledge base. Here you can find detailed information about various aspects of farming and crop management.',
    [SELECTABLE_STRINGS.WIKI_SOWING]: 'Sowing Rate',
    [SELECTABLE_STRINGS.WIKI_COMBINED]: 'Combined Seeding',
    [SELECTABLE_STRINGS.WIKI_CHEMICAL_PROTECTION]: 'Chemical Protection',

    //wiki chemical protection
    [SELECTABLE_STRINGS.WIKI_CHEMICAL_PROTECTION_START_HERE]:
      'Start from here and go to the page of what you want to look up.',
    [SELECTABLE_STRINGS.WIKI_CHEMICAL_PROTECTION_PLANTS]: 'Plants',
    [SELECTABLE_STRINGS.WIKI_CHEMICAL_PROTECTION_ENEMIES]: 'Enemies',
    [SELECTABLE_STRINGS.WIKI_CHEMICAL_PROTECTION_CHEMICALS]: 'Chemicals',
    [SELECTABLE_STRINGS.WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENTS]: 'Active Ingredients',

    //wiki chemical protection active ingredient
    [SELECTABLE_STRINGS.WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_UNIT]: 'Unit',
    [SELECTABLE_STRINGS.WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_CHEMICALS_USING]:
      'Chemicals Using This Ingredient',
    [SELECTABLE_STRINGS.WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_DOSAGE_INFO]:
      'Dosage Information',
    [SELECTABLE_STRINGS.WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_DOSAGE]: 'Dosage',
    [SELECTABLE_STRINGS.WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_MAX_APPLICATIONS]:
      'Max Applications',
    [SELECTABLE_STRINGS.WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_INTERVAL]:
      'Interval Between Applications',
    [SELECTABLE_STRINGS.WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_QUARANTINE]: 'Quarantine Period',
    [SELECTABLE_STRINGS.WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PRICING]: 'Pricing',
    [SELECTABLE_STRINGS.WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PRICE_PER_LITER]: 'Price per 1L',
    [SELECTABLE_STRINGS.WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_PRICE_PER_ACRE]:
      'Price per Acre',
    [SELECTABLE_STRINGS.WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_AFFECTED_PLANTS]:
      'Affected Plants',
    [SELECTABLE_STRINGS.WIKI_CHEMICAL_PROTECTION_ACTIVE_INGREDIENT_ADDITIONAL_INFO]:
      'Additional Information',

    [SELECTABLE_STRINGS.WIKI_COMBINED_PLANT_TYPE]: 'Вид култура',
    [SELECTABLE_STRINGS.WIKI_COMBINED_MIN_SEEDING_RATE]: 'Минимална сеитбена норма',
    [SELECTABLE_STRINGS.WIKI_COMBINED_MAX_SEEDING_RATE]: 'Максимална сеитбена норма',
    [SELECTABLE_STRINGS.WIKI_COMBINED_PRICE_FOR_1KG_SEEDS]: 'Price for 1kg Seeds',
  },
};

export default LangMap;
